### ISSUE TITLE
Create a seed package that pulls in upm packages

### ISSUE THREAD

**Issue by StephenHodgson** [XRTK/XRTK-Core#103]
Ideally we don't want to pull in the whole toolkit using the old `.unitypackage` route, but instead have a package that then installs the upm package.

The reason is that when importing the upm package the old way, the dependencies of the new packages will expect the xrtk to be in the `Packages` folder and in the editor package registry.

This seed package should also add the xrtk upm server registry per #85

**Comment by SimonDarksideJ** [comment]
Ideally, if you deliver a unityasset package, it should not target or depend on the packages folder.  The user should either use the UPM route or the Asset package.

Whilst having an asset that pulls from UPM is good, some may be concerned about mixing things up.

I'd recommed keeping both paths separate, preaching and showing the UPM as the best route (gen we will offer the core as an asset as well using UPM).  But a true .UnityAsset should stay as an asset.  

Make sense?

**Comment by StephenHodgson** [comment]
I think the unity package would just be a single class that adds the XRTK package registry to the upm and then each of the default xrtk packages

**Comment by StephenHodgson** [comment]
That way it _seems_ like we support both. The only downside is if the user is offline. 

But again, Unity doesn't support exporting a `.unitypackage` from the Pacakges location anyway, so I'm not sure how we can support this in our automated delivery system at the moment.

**Comment by SimonDarksideJ** [comment]
I think the package with one class in is the "Default" UPM path, to avoid editing the UPM config file.  Second option is to edit the UPM file.

But as an offline backup, we do need to have a full Asset downloadable that works in Assets, even if it means that some files will need an Asset folder varient.  It's not perfect, but hay, it's Unity

**Comment by StephenHodgson** [comment]
That's why I added the blocked label to it. I opened a bug report but no reply yet.
