### ISSUE TITLE
EditorUserBuildSettings.GetWSADotNetNative is abandoned in 2019

### ISSUE THREAD

**Issue by tattichan** [XRTK/XRTK-Core#11]
**Describe the bug**
In BuildDeployWindow.cs, EditorUserBuildSettings.GetWSADotNetNative occurs error, because of .Net scripting backend is abandoned in Unity2019. 

**Information(please complete the following information):**
 - Version: [2019.1.0.0]

**Comment by StephenHodgson** [comment]
Hi @tattichan, thanks for opening this issue.  

Is this occurring in Unity 2019 beta?
