### ISSUE TITLE
Update Input Actions to reference their profile parent

### ISSUE THREAD

**Issue by StephenHodgson** [XRTK/XRTK-Core#111]
Currently there's no way to distinguish actions from one input action mapping from another.

We should add a reference to the input action profile they're created from to enable easier swap-ability, editing, and customization.

# Requirements

- [x] Minimal changes to profile creation workflow
- [x] Minimal code changes
- [x] No noticeable performance differences between struct vs scriptable object
- [x] `InputActions` can be assigned by object reference or guid.
- [x] Provide a way to convert already established /created `InputAction` profiles with structs to updated scriptable object references

# Acceptance Criteria

- [x] Users can create new Input Actions via profile inspector
- [x] Devs can utilize Input Actions in code to validate input actions from event data
- [x] Users can assign Input Actions in Input Handler components from multiple profiles

# Notes
Care needs to be given in to Action Configuration and Design, to ensure it's not over-complicated, especially if we are merging Actions and Rules.  Ideally, if we are chaining events it should be node based, similar to what is used in Animation for transitions.

Consideration also needs to be given towards inheritance and its role in the new Input Actions extensibility and what that would look like.

**Comment by SimonDarksideJ** [comment]
Added a few more requirements with the suggestion to merge rules and also come considerations

**Comment by StephenHodgson** [comment]
Found an easy way to add profile guid reference without having to do a lot of refactoring 🎉
