### ISSUE TITLE
Assert error every frame demanding "Near plane must be zero for raycast distances to be correct"

### ISSUE THREAD

**Issue by provencher** [XRTK/XRTK-Core#158]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug
Focus provider expects near plane to be zero on UIRaycastCamera, when that makes no sense.
It pops an assert every frame because of this.

## To Reproduce
Open up and configure a blank scene with Lumin setup. Hit play

`Debug.Assert(UIRaycastCamera.nearClipPlane.Equals(0f), "Near plane must be zero for raycast distances to be correct");` will pop from method         `private void RaycastGraphics(IMixedRealityPointer pointer, PointerEventData graphicEventData, LayerMask[] prioritizedLayerMasks, PointerHitResult hitResult)` in the FocusProvider.

## Expected behavior
No assert error every frame.

## Actual behavior
Assert error every frame

## Your Setup (please complete the following information)

- Unity Version 2019.1.0f2
- XRTK Version 0.1.8
- XRTK Lumin configured

## Target Platform (please complete the following information)

- WMR immersive
- OpenVR
- HoloLens
- Lumin

**Comment by StephenHodgson** [comment]
Should be fixed in 0.1.9

**Comment by provencher** [comment]
When's that coming?

**Comment by StephenHodgson** [comment]
Pretty sure that's the latest release, let me double check.

**Comment by StephenHodgson** [comment]
Yup, it's already out, please update and let me know if it still persists.

Fixed in https://github.com/XRTK/XRTK-Core/pull/153

**Comment by provencher** [comment]
I just pulled this evening lol! I'll update and give it a try this week sometime.

Thanks!

**Comment by wassx** [comment]
I tried 0.1.9 on an existing project where same issue ocurrs. Will check for more details.

**Comment by wassx** [comment]
it seems this commit hasn't made it into 0.1.9 https://github.com/XRTK/XRTK-Core/commit/3985a85c6d9d921c8899efe581107f30714714fe

**Comment by dumitrusisianu** [comment]
Near clip plane can be set to zero only if UIRaycastCamera is ortographic (instead of perspective). With ortographic camera, the input seems to be working fine on the Leap, but is not working correctly in the Editor.

**Comment by StephenHodgson** [comment]
My apologies guys. I'll reopen this until it hits release

**Comment by StephenHodgson** [comment]
Closing now that 0.1.10 is released
