### ISSUE TITLE
Canvas Utility can not be added to canvas

### ISSUE THREAD

**Issue by wassx** [XRTK/XRTK-Core#159]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug
After finding all missing scripts on my canvases after porting from mrtk, I try to re-add the canvas utility to make my ui buttons work. But when trying to add the util, it appears in the inspector for a fraction of a second and is removed immediately.

## To Reproduce
1. Create empty object in scene
2. Add ui canvas as a child
3. try to add canvas utility to canvas

## Expected behavior
1 canvas utility ensured on a canvas. If the utility is added automatically on runtime for objects in scene, how should I build prefabs with ui which are added dynamically?

## Actual behavior
It seems that the [DisallowMultipleComponent] in CanvasUtility.cs does not work as expected

## Your Setup (please complete the following information)

- Unity Version 2019.1.1f1
- XRTK Version 0.1.9

## Target Platform (please complete the following information)

- WMR immersive
- HoloLens

## Additional info (workaround)
~~When porting prefabs from mrtk to xrtk and adding the new canvas utility, commenting the [DisallowMultipleComponent] in canvasutility.cs allowed me (sometimes) to add the util.~~

**Comment by wassx** [comment]
After further investigation it seems that the IMixedRealityInputSystem is sometimes null when editing in inspector. As soon as I try to debug, it's there. Some timing issue,...

**Comment by StephenHodgson** [comment]
Thanks for the report, I'll look into this a bit more.
