### ISSUE TITLE
General Discussion: ARFoundation

### ISSUE THREAD

**Issue by FejZa** [XRTK/XRTK-Core#170]
# XRTK - Mixed Reality Toolkit Request for Information

## What are you trying to achieve?

Basically I want XRTK to automagically Setup the ARFoundation session as described in the docs, if I am targeting a compatible platform. I expect to be able to use the same MixedRealityPlayspace object as for any other platform supported by XRTK and not having to Setup Things differently.

My request for Information is: What is the Vision for how XRTK is goind to support this and how I might be able to help Implement it. My approach would be to have a dedicated CameraService e.g. for ARFoundation that will Setup Things as described in the docs etc. I am not familiar enough with XRTK yet to fully understand, how to Implement this without Breaking existing Patterns.

## What have you already tried

I am using ARFoundation in my XRTK Project. But currently basically when Building for mobile AR I am using different Scenes and custom Setups.

## What material have you referenced that didn't answer your question

ARFoundation docs:
https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@1.0/manual/index.html

**Comment by StephenHodgson** [comment]
Thanks for starting this conversation @FejZa. 

We've already got a `CameraService` just for the task, and there's already a [need to add additional components to the camera for the Lumin platform](https://github.com/XRTK/Lumin/issues/19) as well. We should definitely start looking into this asap.

**Comment by FejZa** [comment]
Created #190 to get started with this
