### ISSUE TITLE
Question: Is this repository intended to be used with MRTK as a foundation?

### ISSUE THREAD

**Issue by hridpath** [XRTK/XRTK-Core#18]
After reading the documentation for the [proposed Packaging Guide for MRTK](https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/3418) and reviewing the code contained here, is the intent for this repository to be considered and packaged as an Extension to the MRTK package?

**Comment by StephenHodgson** [comment]
It's up to the consumer of the technology to make a choice about which foundation they can use.

This repository is intended to be a thrid party, core foundation. Large parts of the core implementations are have been updated with important design changes that we felt would seriously impact the end user of the development software and in turn the end user.

**Comment by hridpath** [comment]
Thank you for this clarification
