### ISSUE TITLE
XRTK Controllers & Overall Basic Understanding

### ISSUE THREAD

**Issue by Virtual-Awakening** [XRTK/XRTK-Core#19]
Hello XRTK cybernauts!!

I am extremely happy with the decentralized and holistic approach that XRTK is proposing for developers out there. 

I came across XRTK via a Medium post by Stephen Hodgson who stated in this exciting post the following "Setting up the Mixed Reality Toolkit should be as easy as downloading, importing, and pressing configure" 

( https://medium.com/@stephen_hodgson/getting-to-know-the-new-mixed-reality-toolkit-for-unity-ad21b0e331b1)

However, I must say, despite the amazing job and dedication that has been put to create these tools, at the moment I have found various problems just trying to set up my controllers and almost no documentation or tutorial to get this going smoothly. 

I have read all the documentation in this link: ( https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/mrtk_release/Documentation ).... and yes, it's all great, however, these really didn't give any specific understanding on how to set up my controllers or how to use the scripts in the XRTK to control objects or buttons or any sort of basic event system implementation.

In comparison with the  with HoloToolkit-Unity-Preview-2017.4.3.0 , this was much more straight forward to set up, with a shorter learning curve, as just exploring the different example scenes gave me an understanding of how to implement the controllers and the scripts provided in the package. As well as this great video which really helped me out: https://youtu.be/FrZbmFPiD-E

The downside to it is that is dependent on Unity 2017.4.3.0 and for the VR I am developing I am really looking forward to getting the most of the Shader Graph and the VFX Graph only available in later versions.

I am using Unity 2018.3.0f2 and after setting up a basic scene, my Samsung Odessey gets recognized by the configuration of XRTK, however, my controllers are not appearing in the scene and I notice that my controller input name does not appear in the input manager. 

So, I really hope the developers of XRTK could help me and also any future developer that stumbles upon this post to get more information on the basic setup of the Motion Controllers, and any overall basic understanding of how to use this promising Toolkit. 

Best Wishes

**Comment by SimonDarksideJ** [comment]
Did you try watching this video which is a quickstart to getting up and running with the MRTK/XRTK?
Walks through most basic things.

As to setting up controllers, once your basic scene is up and running, you simply need to create your own version of the Input / Controller Mapping configurations to start sculpting your own experience.

I plan to get a great many more videos done on the config side as soon as I'm able :D

**Comment by Virtual-Awakening** [comment]
Thanks for your quick response and for sharing that very useful video, Simon :) 

I have followed the steps outlined in the video, and also I have tried to create my own version of the Input / Controller Mapping configuration, but I am getting an error by Unity when I try to create a new profile:

> Instance of BaseMixedRealityControllerMappingProfile couldn't be created. The script class needs to derive from ScriptableObject.

![controller mapping error](https://user-images.githubusercontent.com/26207682/52589679-5a070800-2e37-11e9-93bc-edd745c3173e.PNG)

Is there anything I'm missing?... In your video tutorial seems that MRTK recognizes your controllers straight away. 

Looking forward to your upcoming tutorials :)

**Comment by wassx** [comment]
Had the same issue. This is unity related as the `BaseMixedRealityControllerMappingProfile` is `abstract`
See: https://answers.unity.com/questions/1318684/the-the-script-class-needs-to-derive-from-scriptab.html
When removing the "abstract" in worked to create a new one. But I'm not sure this is the way to go.

**Comment by SimonDarksideJ** [comment]
Very curious, not had that myself.  I'll look in to that today.

**Comment by wassx** [comment]
I think this is somehow related to the issue in `BaseController:111` where the controllerMappings.ControllerType.Type is always "(None)" instead of the controllerType "WindowsMixedRealityController". Hence always a warning appears:

> No controller profile found for type WindowsMixedRealityController, please ensure all controllers are defined in the configured MixedRealityControllerConfigurationProfile.

**Comment by SimonDarksideJ** [comment]
I have a slight workaround, you can create your own controller mappings for specific controllers using the asset comments, so you can create a new "WindowsMixedRealityControllerMapping" from "Create -> Mixed Reality Toolkit -> Mixed Reality Controller Mappings -> (Controller Type)" which creates the custom asset
You can then assign this to the relevant slot in the "MixedRealityControllerMappingProfiles" config and this works.

It's only the "Copy and Customise" button that isn't working, which is "very" odd as it does this for all controllers.  But I suspect you are correct @wassx that it has something to do with the "Type" of controller it's trying to copy and possibly it's null.

**Comment by SimonDarksideJ** [comment]
Found it, basically, we shouldn't have a "Copy / Customise" button on that inspector for the multiple profiles option.  As the "Type" of controller in that list is the "BaseMixedRealityontrollerMapping" which isn't a concrete type of scriptable object, as it's abstract.

Simplest answer is to remove that button, you should either replace the existing profile with a new one, or simply add another. Can review later if this can be "improved"
(Gee's I used a lot of "" today)

**Comment by SimonDarksideJ** [comment]
Interestingly, this highlights some other issues on the screen, e.g:
* Can't add a duplicate profile (which you shouldn't) but there is no feedback as to why it didn't work.
* You can add multiple mappings of different names for the same type (e.g. two different MRControllerMappings if they have different names), need to review if this should or should not happen.

**Comment by wassx** [comment]
> Simplest answer is to remove that button, you should either replace the existing profile with a new one, or simply add another. Can review later if this can be "improved"

As far as I understand this button should do the same as the button in the "Create.." context menu? I'll give it a try.

**Comment by Virtual-Awakening** [comment]
> I have a slight workaround, you can create your own controller mappings for specific controllers using the asset comments, so you can create a new "WindowsMixedRealityControllerMapping" from "Create -> Mixed Reality Toolkit -> Mixed Reality Controller Mappings -> (Controller Type)" which creates the custom asset
> You can then assign this to the relevant slot in the "MixedRealityControllerMappingProfiles" config and this works.

Thanks for the support!!

I have successfully created a new profile following your workaround provided above, however, even if my controllers are paired and ready in the Mixed Reality Portal, the motion controllers are still not being recognised by Unity or XRTK. 

When I hit play only these prefabs are opening as children of the MixedRealityPlayspace game object:

![controllers not apearing](https://user-images.githubusercontent.com/26207682/52648078-c9cfce00-2edd-11e9-9a09-f05c3584a91e.PNG)

I see that in your tutorial, MRTK adds the following prefabs in play mode:

![mrtk tutorial mrplayspace gameobject](https://user-images.githubusercontent.com/26207682/52648244-174c3b00-2ede-11e9-8272-4bb8143bbe9b.PNG)

The only difference in comparison to your tutorial is the version of Unity that I am using (the one that XRTK requires)

Still not sure if its Unity, XRTK or something that I haven't done to set this correctly.

Appreciate both of your help and time.

**Comment by hridpath** [comment]
Any documentation, rough drafts or outlines, about the individual profiles? When creating a new profile and it is all blank, It is difficult to know where to start.

**Comment by StephenHodgson** [comment]
Creating new profiles is more of an advanced topic. Simply copying the default profiles is always the best start.

**Comment by SimonDarksideJ** [comment]
Issue with the controllers not displaying was due to a default asset bug, PR #23 submitted to resolve this.  I believe an updated release will also come out to push this.

As for docs @hridpath , I'll be doing some light touches to get you started.

**Comment by Virtual-Awakening** [comment]
I found a way to make the controllers appear by going into the "Controller Data Provider Profile", under the "Windows Mixed Reality Controller Data" Provider in the "Runtime Platform" I changed it from "Nothing" to "Everything" and then my controllers appeared in the scene :) 

However, all the inputs I mapped in the "Controller Mapping Profiles" are not working, there is no pointer, neither teleportation system, and the controllers disappear if I move to some areas of the scene 

:(

**Comment by StephenHodgson** [comment]
Are you using the default profiles?

**Comment by Virtual-Awakening** [comment]
Yes @StephenHodgson, I have been creating direct copies of the default profiles for being able to get deeper into the settings.

**Comment by Virtual-Awakening** [comment]
Alright, Its fixed for now.

What I did was to start everything again, new scene, new profiles from the default and new profiles in various of the "Input System Settings".

The only change from the default profiles, was in the "Controller Data Provider Profile", under the "Windows Mixed Reality Controller Data" Provider in the "Runtime Platform" I changed it from "Windows StandAlone" to "Everything"

**Comment by StephenHodgson** [comment]
Okay thanks for the report. We also fixed one problem with the windows mixed reality controller profile as well. I'll try to push out an update today for it.

**Comment by SimonDarksideJ** [comment]
Hi @Virtual-Awakening , can you retest under the latest Dev or Master branches (they are back in sync now) and check if you're ok, if so then close the issue please.
