### ISSUE TITLE
Initialize ARFoundation session

### ISSUE THREAD

**Issue by FejZa** [XRTK/XRTK-Core#190]
# XRTK - Mixed Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

Opening a new feature request as part of the general Arfoundation support discussed in #170. The first step to have ARFoundatin working is to properly Setup the session.

## How would you classify your suggestion

- New platform support

## Describe the solution you'd like

For ARFoundation to work, the following steps Need to be implemtend:

- [ ] Create `ARSession` component when running with ARFoundation enabled. It can be added to any GameObject. Fort XRTK preferably to the playspace GO
- [ ] Create `ARSessionOrigin` component, probably also best added to the playspace GO
- [ ] Add `TrackedPoseDriver` to main camera
- [ ] Implement to optionally add `ARCameraBackground` to the main camrea GO so the video feed is rendered to the background

## Additional context

https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@1.0/manual/index.html

**Comment by StephenHodgson** [comment]
After some of the announcements from Unite I'm not sure I want to try and support ARFoundation. Likely there's gonna be conflicts between the XRTK and unity's XR offerings.

**Comment by FejZa** [comment]
@StephenHodgson from what I have learned since I created this PR personally I don't see how / why XRTK should support ARFoundation, since they are somewhat converging to become "competitors". ARFoundation is currently a subset of what XRTK already is and just an abstarction layer. IMHO this PR is obsolete.
