### ISSUE TITLE
Type or namespace name 'ExecuteEvents' could not be found

### ISSUE THREAD

**Issue by hridpath** [XRTK/XRTK-Core#200]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug
Reciving the following error in Unity Console:
```
Failed to register the MixedRealityInputSystem service: System.Exception - The Input system is missing the required GazeProviderType!
  at XRTK.Services.InputSystem.MixedRealityInputSystem..ctor (XRTK.Definitions.InputSystem.MixedRealityInputSystemProfile profile) [0x000da] in O:\Git\Source\Repos\XRTK\XRTK-Core\XRTK-Core\Assets\XRTK\Services\InputSystem\MixedRealityInputSystem.cs:44 

  at (wrapper managed-to-native) System.Reflection.MonoCMethod.InternalInvoke(System.Reflection.MonoCMethod,object,object[],System.Exception&)

  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00002] in <1f0c1ef1ad524c38bbc5536809c46b48>:0 
UnityEngine.Debug:LogError(Object)
XRTK.Services.MixedRealityToolkit:CreateAndRegisterService(Type, SupportedPlatforms, Object[]) (at Assets/XRTK/Services/MixedRealityToolkit.cs:888)
XRTK.Services.MixedRealityToolkit:CreateAndRegisterService(Type, Object[]) (at Assets/XRTK/Services/MixedRealityToolkit.cs:833)
XRTK.Services.MixedRealityToolkit:InitializeServiceLocator() (at Assets/XRTK/Services/MixedRealityToolkit.cs:383)
XRTK.Services.MixedRealityToolkit:InitializeInstance() (at Assets/XRTK/Services/MixedRealityToolkit.cs:282)
XRTK.Services.MixedRealityToolkit:get_Instance() (at Assets/XRTK/Services/MixedRealityToolkit.cs:206)
XRTK.Services.MixedRealityToolkit:ConfirmInitialized() (at Assets/XRTK/Services/MixedRealityToolkit.cs:319)
XRTK.Inspectors.Utilities.MixedRealityInspectorUtility:CheckMixedRealityConfigured(Boolean) (at Assets/XRTK/Inspectors/Utilities/MixedRealityInspectorUtility.cs:45)
XRTK.Inspectors.Profiles.MixedRealityCameraProfileInspector:OnEnable() (at Assets/XRTK/Inspectors/Profiles/MixedRealityCameraProfileInspector.cs:33)
```

## To Reproduce

1. New Unity Project. Closed Unity
2. Manually added XRTK package manager dependency for v. 01.11
3. Opened Unity and saw the XRTK.Core package added in Project/Packages
4. Closed and reopened Unity Project
5. Got prompt to "Apply Mixed Reality Toolkit Default Settings" clicked apply.
6. Recieved error about the xrtk package cache and did not get the menu for XRTK.
```
_Library\PackageCache\com.xrtk.core@f6a39a3fce074f7de2e6dc0153839d9ebcfeabf4\Services\InputSystem\MixedRealityInputSystem.cs(1252,33): error CS0246: The type or namespace name 'ExecuteEvents' could not be found (are you missing a using directive or an assembly reference?)
```
7. Closed project and deleted cache
8. Opened project and observed the downloading of the xrtk package again.
9.  Recieved same error.
10. Insured that the Player settings for XR is set to WMR. This downloaded the Window Mixed Reality package.
11. Re-started Unity Project
12. Not able to proceed

## Expected behavior

Complete download and install of package with no errors.

## Actual behavior

Errors.

## Screenshots

XRTK Import settings:
![image](https://user-images.githubusercontent.com/15804010/58290155-910d8380-7d6d-11e9-9f2d-8f2d7b291185.png)

![image](https://user-images.githubusercontent.com/15804010/58290189-ae425200-7d6d-11e9-9d36-f30e5aa1239c.png)

## Your Setup (please complete the following information)

- Unity Version [e.g. 2019.2.0b1]
- XRTK Version [e.g. 0.1.11]

## Target Platform (please complete the following information)

- WMR immersive
- HoloLens

**Comment by StephenHodgson** [comment]
Did all of the packages load in?

Did you have the SDK, WMR, and the rest of the packages?

**Comment by SimonDarksideJ** [comment]
> Did you have the SDK, WMR, and the rest of the packages?
We should check the WMR package includes a dependency to the Unity.WMR package.  but this is automatically installed when you enable VR on UWP

> Unity Version [e.g. 2019.2.0b1]
Going to re-test again today with these replication instructions, but all testing has been on 2019.1, don't think we have tested 2019.2 yet but I would be surprised if they broke something again (actually no, I wouldn't be surprised at all, because Unity.....)

**Comment by SimonDarksideJ** [comment]
Right, I have an answer, but no solution yet.

Unity Removed the UI system from 2019.2.  I do recall they were updating the UI system and refreshing stuff, but something has obviously changed.  

Investigating

**Comment by SimonDarksideJ** [comment]
Right, so basically, Unity have MOVED the UI system wholely to a UPM package in 2019.2, so we need to include that as a package reference in solutions that use.

Started some fixed to help resolve the situation and make it future proof.

**Comment by hridpath** [comment]
@StephenHodgson The SDK did not load either.

**Comment by SimonDarksideJ** [comment]
It was a cascade of events, Core could not compile due to Missing references (UI System), UPM could not download as it didn't recognise your schema.
Found another but, it originally showed up as an obsolete warning, but is now showing as an error.  They deprecated two Linux platform entries in the BuildSettings.Platforms.

Testing again tomorrow, progress at least

**Comment by SimonDarksideJ** [comment]
As expected stepping stones.  the SDK needs the same asmdef fix.
However, the fix on the upm front needs a bit more attention but isn't a showstopper

**Comment by SimonDarksideJ** [comment]
Not quite closed yet. Still testing :D

**Comment by StephenHodgson** [comment]
Oh, my apologies.

**Comment by StephenHodgson** [comment]
@SimonDarksideJ is this tested?

**Comment by SimonDarksideJ** [comment]
Finished testing on 2019.2 with the latest dev release. All working fine now
