### ISSUE TITLE
Configure and Play does not add the scene to the Build settings

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#207]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

The Configure option checks and validates if the current scene is in the build settings, as well as a scene with the MRToolkit.
However, hitting "Configure and Play" in the prompt does check if the Toolkit is in the current scene, it doesn't add it to the build settings and hence the prompt always appears, even if the current scene is configured for the toolkit

## To Reproduce

1. Create new project
2. Import the XRTK and configure
3. Create new scene
4. hit play
5. Stop scene and observe toolkit is in scene
6. hit play again

## Expected behavior

hitting "Configure and Play" should configure everything needed for the checks it performs

## Actual behavior

"Configure and Play" prompt always appears, even if the scene is configured (likely as it's not in the build scenes list.

## Your Setup (please complete the following information)

- Unity Version 2019.1.4f1
- XRTK Version 0.1.11

## Target Platform (please complete the following information)

- Any

## Additional Notes

Observed the checks no longer validate IL2CPP or VR enabled. Can run the project without VR enabled?

**Comment by StephenHodgson** [comment]
Pretty sure this is a Unity bug.

Sometimes the unity method there where it's supposed to call save scene if user wants to doesn't get called by the editor correctly

**Comment by StephenHodgson** [comment]
Pretty sure I fixed this with the last release.
