### ISSUE TITLE
Null Ref exception when a profile has no parent

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#209]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

If a user creates a profile manually, it has no parent.  If this profile is also then edited before it is assigned to a profile, this null parent causes an exception 

```
Library/PackageCache/com.xrtk.core@f6a39a3fce074f7de2e6dc0153839d9ebcfeabf4/Inspectors/ControllerPopupWindow.cs:107 
```

## To Reproduce

1. Create a new profile using the editor menu (e.g. Create -> Mixed Reality Toolkit -> Input System -> Controllers Mappings -> xxx)
2. Open the profile in the inspector directly
3. Click button to open profile
4. Error

## Expected behavior

No Errors

## Actual behavior

Error, although it is not critical and doesn't stop the editor.  Should not error.

## Your Setup (please complete the following information)

- Unity Version 2019.1.4f1
- XRTK Version 0.1.11

## Target Platform (please complete the following information)

- Any

## Additional context

```
NullReferenceException: Object reference not set to an instance of an object
XRTK.Inspectors.ControllerPopupWindow.OnFocus () (at Library/PackageCache/com.xrtk.core@f6a39a3fce074f7de2e6dc0153839d9ebcfeabf4/Inspectors/ControllerPopupWindow.cs:107)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:345)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:339)
UnityEditor.HostView.OnFocus () (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:154)
UnityEditor.EditorWindow:ShowUtility()
XRTK.Inspectors.ControllerPopupWindow:Show(BaseMixedRealityControllerMappingProfile, SupportedControllerType, SerializedProperty, Handedness, Boolean) (at Library/PackageCache/com.xrtk.core@f6a39a3fce074f7de2e6dc0153839d9ebcfeabf4/Inspectors/ControllerPopupWindow.cs:256)
XRTK.Inspectors.Profiles.<>c__DisplayClass6_0:<OnInspectorGUI>b__0() (at Library/PackageCache/com.xrtk.core@f6a39a3fce074f7de2e6dc0153839d9ebcfeabf4/Inspectors/Profiles/BaseMixedRealityControllerMappingProfileInspector.cs:136)
UnityEditor.EditorApplication:Internal_CallDelayFunctions()
```

**Comment by StephenHodgson** [comment]
I think I'm going to remove the ability to create profiles though the context menu.

I think it's better if we funnel people though the main configuration profile to create these.

**Comment by SimonDarksideJ** [comment]
That's fine, so long as we look to improve the GUI for managing profiles :D

**Comment by FejZa** [comment]
Just had this issue and was gong to create a new bug report when GitHub suggested this existing issue to me. I see it's been around for awhile. So the solution will be to just remove profile creating using the menu?

**Comment by StephenHodgson** [comment]
The best workaround for this atm is to make sure the profile is referenced someplace in the main configuration profile and make sure you've selected it at least once. In the future I'd like to have a window pop up to assign a parent.
