### ISSUE TITLE
XRTK breaks when MRTK is imported alongside

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#218]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

Several meta files were ported to the MRTK, which causes an incompatibility conflict when the MRTK and XRTK are in the same project.  The meta files affected include:

* BuildDeployWindow.cs.meta
* BuildInfoExtensions.cs.meta
* IBuildInfo.cs.meta
* README.md.meta
* UnityPlayerBuildTools.cs.meta
* UwpBuildDeployPreferences.cs.meta
* UwpBuildInfo.cs.meta
* EditorPreferences.cs.meta

To resolve this, the meta files need to be regenerated in the XRTK

## To Reproduce

1. New project
2. Import XRTK
3. Import MRTK
4. Observe missing classes errors

## Expected behavior

XRTK and MRTK should exist in the same project

## Actual behavior

Errors galore 

## Your Setup (please complete the following information)

- Unity Version 2019.1.7
- XRTK Version 0.1.11

## Target Platform (please complete the following information)

- Any

**Comment by StephenHodgson** [comment]
I'll regenerate the meta files for those. Shouldn't affect anything.

**Comment by StephenHodgson** [comment]
@SimonDarksideJ which README.md.meta file are you referring to?
