### ISSUE TITLE
Add the build version time / date to the diagnostics display

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#229]
# XRTK - Mixed Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

It's been suggested that it is very useful to have the build version/time/date displayed in a debug app, to ensure you are actually running the build you expect.  This is especially critical on platforms (like Android) where you don't have the project directly running/connected to Unity.

## How would you classify your suggestion

- Usability / Configuration

## Describe the solution you'd like

The diagnostics view should have a header showing:
* The current build version
* The build time/date

Ideally, there should also be another debug option/popup when the diagnostic view is hidden/removed for test / QA builds.  With properties to expose on the XRTK itself.

## Describe alternatives you've considered

Wiring it up manually

**Comment by MephestoKhaan** [comment]
This is what I do:
```
class DateStamp : IPreprocessBuildWithReport
{
	public int callbackOrder { get { return 0; } }
	
	public void OnPreprocessBuild(BuildReport report)
	{
		Text label = GameObject.FindGameObjectWithTag("DateStamp").GetComponent<Text>();
		System.DateTime now = System.DateTime.Now;
		label.text = string.Format("{0}  {1}",now.ToShortDateString(), now.ToShortTimeString());
	}
}
```

Don't know where to put it right now in this project but I leave this code as a suggestion/to save time, a better way of finding the Gameobject would be needed etc.

**Comment by StephenHodgson** [comment]
Should be easy enough to get the build version and time from the built executable via name.

We could also put in a special scriptable object that can keep track of this diagnostic data.

**Comment by StephenHodgson** [comment]
Gonna knock this out this week.

**Comment by SimonDarksideJ** [comment]
make it for the next release 🗡
