### ISSUE TITLE
Controller mapping unification across platforms

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#240]
# XRTK - Mixed Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

Currently, multiple mappings are required for the same controller across platforms
(With the exception of WMR).  E.G. Separate mapping profiles required for Oculus Touch on OpenVR and Native Oculus (due to differences in how mapping works)

Ideally, this should be unified so a controller type only needs mapping once for all supported platforms

## How would you classify your suggestion

- Usability / Configuration
- Architecture / Services

## Describe the solution you'd like

One mapping per controller type (same as WMR is currently implemented)

**Comment by StephenHodgson** [comment]
Good luck with that, each is technically a different `Type` under the hood. While yes the mappings usually match up across OpenVR vs the native platform it's not always the case.
