### ISSUE TITLE
Enable XRTK to provide by default, support for Long press and double click

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#258]
# XRTK - Mixed Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

After reviewing the NReal specification, they make full use of the limited controls on their 3Dof controller, for example, having the following on their trackpad:

* Click - SelectManipulation 
* Hold- DragManipulation 
* Double Click - Lock-on

They also have Press and Long Press as additional actions.

Granted, today developers can implement this themselves, however as this is likely to become a more common scenario, the XRTK should try and provide some facility for this either as SDK components or preferably as new input action rules.

## How would you classify your suggestion

- Usability / Configuration

## Describe the solution you'd like

Either:

* Deliver new SDK components to enable double click and long press
* Enhance Input Action Rules to enable any input to also generate Double-Click or Long Press

## Describe alternatives you've considered

Leaving it to the developer :S

## Additional context

http://developer.nreal.ai/design/controlling

**Comment by StephenHodgson** [comment]
Likely this will be a UI/UX Implementation

**Comment by SimonDarksideJ** [comment]
My first thought is that it should be a UX component.  But the tinkerer in me also feels a Rules implementation would be far more useful :P

**Comment by StephenHodgson** [comment]
Rules were intended to transform one action into another and carry along any relevant data.
While I can see some benefit to this, it's not supposed to change the timing of those actions.

**Comment by StephenHodgson** [comment]
I'm going to address this with #111

**Comment by SimonDarksideJ** [comment]
Long Press and Double press are ADDITIONAL actions on top of the existing.  You would get the normal press event, but you should be able to configure another event once the criteria is met, e.g. 2 events within a certain window (double click), repeated event over a certain span of time (Hold).

Granted the developer could implement these themselves, but it makes more sense the framework provides a simpler generic implementation for any control.

I agree this should potentially be implemented in #111 , so long as it accounts it as an additional event from a control

**Comment by StephenHodgson** [comment]
Awesome feedback. Those things will definitely be employed in the feature.
