### ISSUE TITLE
Rending problems on Lumin

### ISSUE THREAD

**Issue by StephenHodgson** [XRTK/XRTK-Core#263]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

Lumin no longer renders properly (only left eye) after the updates to the Mixed Reality Standard shader.

I'm also getting these errors when building:
```
Shader error in 'Mixed Reality Toolkit/Wireframe': variable 'o' used without having been completely initialized at line 119 (on gles3)
Compiling Vertex program with STEREO_INSTANCING_ON
Platform defines: UNITY_NO_DXT5nm UNITY_NO_RGBM UNITY_ENABLE_REFLECTION_BUFFERS UNITY_FRAMEBUFFER_FETCH_AVAILABLE UNITY_NO_CUBEMAP_ARRAY UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_MOBILE UNITY_LIGHTMAP_DLDR_ENCODING

Shader error in 'Mixed Reality Toolkit/Wireframe': variable 'o' used without having been completely initialized at line 119 (on glcore)
Compiling Vertex program with STEREO_INSTANCING_ON
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_NO_CUBEMAP_ARRAY UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_DLDR_ENCODING
```

## To Reproduce

1. Switch to lumin build target
2. open build window
3. Build

## Expected behavior

Should render in both eyes

## Actual behavior

Only renders in left eye

## Screenshots

![image](https://user-images.githubusercontent.com/13334553/62559138-5e413a80-b848-11e9-92f2-d84d02d6782b.png)

## Your Setup (please complete the following information)

- Unity Version 2019.1.12f1
- XRTK Version 6e6ef36f7d91aafa7b4892ae39f322b4f3b9a739

## Target Platform (please complete the following information)

- Lumin (Magic Leap)

**Comment by SimonDarksideJ** [comment]
The first part does worry me greatly, as to how that could even happen.
Hoping Ronald is back now to comment on the second part.

Likely we'll need to rollback the shaders based on this feedback

**Comment by mo-spatial** [comment]
FYI if you guys want the fix for MRTK standard shader to render in both eyes on Lumin you only need to make the following modifications:

![Screen Shot 2019-12-03 at 5 06 00 PM](https://user-images.githubusercontent.com/52168927/70093823-393eb780-15ef-11ea-8734-6a75c8fcbc3a.png)

**Comment by StephenHodgson** [comment]
Thanks!

Really we ought to update to the universal render pipeline as soon as we can through tbh.
