### ISSUE TITLE
Is there a place for dev discussion / planning for the future of XRTK?

### ISSUE THREAD

**Issue by jamcar23** [XRTK/XRTK-Core#27]
I know there's a [Project Setup](https://github.com/XRTK/XRTK-Core/projects/1) project as well as a Roadmap in the README but is there another place for devs to discuss the state of current / future development of this project?

If not I propose we use Issues as a way to do this publicly. If we do use Issue then I think it would be a good idea to add new Labels such as Discussion, Proposal, Feature, WIP, as well as labels for each platform (WMR, OpenVR, Lumin, etc.)

**Comment by StephenHodgson** [comment]
Hi, @jamcar23 these are wonderful proposals.

We do need to add/update our road map as well as getting a better idea of where everyone would like to see this project go.

At the moment for real-time-discussions we've been using slack as a way to communicate in near real time.

**Comment by jamcar23** [comment]
@StephenHodgson  are you accepting new members to the slack channel? I would be interested in joining if so. 

I think there's a huge need for a generic cross platform XR library that makes it easier for devs to support a variety of devices from a single API and I would be happy to help develop said library. Right now I'm trying to gather info on exist projects, such as XRTK, to see if it would be better to contribute to one of those or to start my own project.

**Comment by StephenHodgson** [comment]
Sorry for the late reply.

https://holodevelopers.slack.com

**Comment by jamcar23** [comment]
@StephenHodgson that link only lets me sign into an account in that workspace. Can you send me a link that will let me join the workspace or invite me with my email: jamcar23@gmail.com ?

**Comment by Jarodshow** [comment]
You can use this automatic invite sender:

https://holodevelopersslack.azurewebsites.net/

**Comment by StephenHodgson** [comment]
Even better!

**Comment by jamcar23** [comment]
@Jarodshow Awesome thanks!

**Comment by jamcar23** [comment]
I checked out the slack workspace and, unless I missed something, it seems to be more of a generic Hololens developer workspace rather than being related to XRTK (there are only a few places where XRTK is mentioned). If I did miss something, can you please point me to where I should be looking? If I didn't miss anything and that workspace is geared toward Hololens development then I think it would be a good idea to create our own workspace which is specifically geared towards XRTK, especially because as XRTK matures it should have less to do with any specific platform. What do you all think about this? 

Ultimately I'm trying to figure out what's on the mind of the current developers. I would like to start contributing code, as I have a project that is targeting multiple XR devices and would greatly benefit from a more mature XRTK, but I also don't want to step on anyone's toes or do something that goes against plans the current devs have. If there isn't any docs like this then I'll start contributing / propose features where I see fit, I guess?

**Comment by StephenHodgson** [comment]
Please do!

Yeah that slack channel started out as a general purpose discussion group. You can PM me directly or chat in the mixed-reality-toolkit channel.

**Comment by SimonDarksideJ** [comment]
For XRTK specific stuff, stick with the XRTK channel.
For more generic or device specific chat, then use the appropriate channels, e.g. Virtual Reality, Magic Leap, etc.

**Comment by StephenHodgson** [comment]
@jamcar23 if you'd like me to add you to the xrtk org, I can. 

We're open to anyone who'd like to join us and you'll have access to updating tasks and projects with us.
