### ISSUE TITLE
XRTK packages are locked in the UPM window and cannot be removed

### ISSUE THREAD

**Issue by FejZa** [XRTK/XRTK-Core#274]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

XRTK package, such as the WMR module, or Oculus etc. are locked in the UPM package manager window and cannot be removed / uninstalled using that "Unity native UI". Instead the are only removable using the custom XRTK package manager window.

## To Reproduce

1. Import XRTK
2 Observe all XRTK package have been initially installed
3. Decide you don't need WMR
4. Open Unity package mangaer window
5. Select XRTK.WindowsMixedReality
6. Observe the Remove button is grayed out / disabled and you cannot uninstall

## Expected behavior

I can either use the XRTK custom package manager or the UPM package manager window to uninstall packages I don't need.

## Actual behavior

Can't uninstall via UPM.

**Comment by SimonDarksideJ** [comment]
This has been discussed and will be updated after 0.15.  The plan is to have the platforms OFF by default and you simply use the XRTK menu or edit the PackageAsset config file to add the ones you want.

**Comment by FejZa** [comment]
I understand, but it's a different topic. This one is about not being able to remove packages via UPM window.

**Comment by SimonDarksideJ** [comment]
You don't / can't, you have to use the XRTK package management functions to do it.  Limitation by Unity themselves, we can only do it programmatically (or edit the manifest manually)

Until suck time that Unity open up the package manager

**Comment by StephenHodgson** [comment]
> You don't / can't, you have to use the XRTK package management functions to do it. Limitation by Unity themselves, we can only do it programmatically (or edit the manifest manually)

> Until suck time that Unity open up the package manager

Not entirely true. You can remove them, but the package check puts them back.

**Comment by SimonDarksideJ** [comment]
I updated my response Stephen :P
