### ISSUE TITLE
Wrong namespaces assigned to controller definitions

### ISSUE THREAD

**Issue by FejZa** [XRTK/XRTK-Core#283]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

All code files in `XRTK-Core/Definitions/Controllers` have the namespace `XRTK.Providers.Controllers` instead of `XRTK.Definitions.Controllers`. They either need to be moved into the `XRTK-Core/Providres/Controllers` folder or have their namespace adjusted.

**Comment by SimonDarksideJ** [comment]
God spotting @FejZa 
What're your thoughts @StephenHodgson ?  This should be a non-breaking change as they are only used internally

**Comment by StephenHodgson** [comment]
If we change the namespace we gotta update all the profiles that have controller data serialized.

Pretty big breaking change but I'm fine doing it

**Comment by SimonDarksideJ** [comment]
Well, as @fejZa said, the other option is to move the files to the correct folder. Which is the simpler solution if the folder is fine with you. I've no issue with the folder suggested as it's in line with the extension packages

**Comment by StephenHodgson** [comment]
I don't mind just updating the namespace. The folder structure is correct.
