### ISSUE TITLE
Update message when MRConfig is not found and enable easier access to the MR Base scene

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#289]
# XRTK - Mixed Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

With the addition of the MR Base scene, the error text to add the MR config is no longer valid and needs updating.
Also with the recommendation that the MR Base scene should be used, there should also be a simple way to add the base scene to the currently editing scene list.

![image](https://user-images.githubusercontent.com/1793042/63011324-ff9b4280-be7f-11e9-80fe-16debdf384a2.png)

## How would you classify your suggestion

- Usability / Configuration

## Describe the solution you'd like

The warning when no config is found should be updated to:
"No Mixed Reality Toolkit found in scene. Consider adding the base scene for editing"

Additionally, there should be an easy to use button to do this for the user automatically if they wish.

## Describe alternatives you've considered

Fudging it manually with a spoon

**Comment by StephenHodgson** [comment]
Currently when you configure the toolkit the base scene is set for you.

And if a user wants to update the scene they can go to the XRTK preferences to update or press configure again in the scene that they want to use as the base scene.

I suppose really the only other thing we would want to do is load in the base scene if one is set if we don't detect a valid active configuration.

**Comment by StephenHodgson** [comment]
I removed the requirement altogether to need a reference to the service locator.
