### ISSUE TITLE
Near/Far interactions with BaseControllerPointer

### ISSUE THREAD

**Issue by StephenHodgson** [XRTK/XRTK-Core#293]
# XRTK - Mixed Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

To help facilitate the Near/Far interaction requirements for Articulated Hands, we'll need to update the `BaseControllerPointer` to utilize near/far interactions.

**Near Interactions:** - Actions raised when a pointer hit is detected between the UI element's collider and the pointers collider.

**Far Interactions:** - Actions raised when a pointer hit is detected using raycasting.

## How would you classify your suggestion

- Usability / Configuration
- Architecture / Services

## Acceptance Criteria

- [x] Developers can adjust the near action colliders distance along the pointer ray path.
- [x] Developers can get events from near interactions as input and pointer events.

**Comment by provencher** [comment]
One thing to consider is that with hand tracking you can't really manually place colliders - you need to generate them procedurally since everyone has different hand sizes.

**Comment by StephenHodgson** [comment]
Right, these were just configuration options for the pointer inspectors
