### ISSUE TITLE
Latest package versions don't properly get pulled down.

### ISSUE THREAD

**Issue by StephenHodgson** [XRTK/XRTK-Core#300]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

If the upm package extension doesn't get installed first, then the later packages will fail to install the latest versions.

## To Reproduce

1. Create a new project
2. Import the seed package or manually reference the xrtk package in the manifest.json
3. Wait for import

## Your Setup (please complete the following information)

- Unity Version 2019.1.14f1
- XRTK Version 0.1.17
- XRTK.SDK 0.1.12
- XRTK.UPM 0.9.6

## Additional context

Seems to be happening because the UPM extension package isn't installed first?

In either case, the versioning is not putting the 0.1.12 ahead of 0.1.9 (which is the version that installed)

**Comment by StephenHodgson** [comment]
I think the easiest way to fix this for now is to bump the version to 0.2.0, then fix it properly

**Comment by SimonDarksideJ** [comment]
Let's keep this issue open until the next Core release, or possible to an interim release to deploy this fix.
Else users are going to be scratching their heads as to why it isn't working @StephenHodgson

**Comment by StephenHodgson** [comment]
Fine but let's also add a label that says resolved with next release or something along those lines

**Comment by SimonDarksideJ** [comment]
Can only be closed once it's been tested in the release UPM build

**Comment by StephenHodgson** [comment]
Tested. Seems to be working now.
