### ISSUE TITLE
XRTK-Core 0.1.19 does not  pull all dependencies

### ISSUE THREAD

**Issue by milos12345** [XRTK/XRTK-Core#325]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

Edited manifest as per instructions for XRTK-Core 0.1.19

## To Reproduce

New Scene, Edit manifest.json per instructions in Release

## Expected behavior

All dependencies are downloaded (it worked for 0.1.18)

## Actual behavior

Only XRTK.Core is downloaded

## Your Setup (please complete the following information)

- Unity Version [e.g. 2019.1.14f1]
- XRTK Version [e.g. 0.1.19]

## Target Platform (please complete the following information)

- WMR immersive
- OpenVR

**Comment by StephenHodgson** [comment]
What dependencies were not pulled as expected?

**Comment by StephenHodgson** [comment]
We removed it because it was causing crashing errors and longer startup times. 

Once the core package is in the project you should be able to add all of the packages via upm package manager

**Comment by milos12345** [comment]
Got it, I prefer it the new way. It will be helpful to make a note in Release section that it should be done through Package Manager. In 5 years working with Unity I have not needed the Package Manager, so I would not even look there, and there are probably more users like me.

**Comment by StephenHodgson** [comment]
Will do! thanks for the feedback 😃

**Comment by StephenHodgson** [comment]
Looks like we'll attempt to at least pull in the SDK and let users decide which platforms they want to install.

See #333 333
