### ISSUE TITLE
If the UPM package for a platform is not installed, Several hard errors are presented in the console

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#330]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

Most platforms require a dependant UPM package installed for it to function, e.g. Oculus (Standalone/Android), WMR and Lumin.

Currently, if the data provider is registered for a platform and the corresponding UPM package is not installed, this results in several spurious error messages saying the data provider could not be initialised.

This error should be a lot friendlier for a simple project setup issue

## To Reproduce

1. Install XRTK.Core and SDK using the Unity Package Manager
2. Create a new Scene and use "Mixed Reality Toolkit -> Configure..."
3. See errors

Windows Standalone - Errors about Oculus
UWP - Errors about WMR extensions
Lumin - Errors about Lumin

## Expected behavior

User should receive a warning advising to check the installed UPM packages

## Actual behavior

Errors and no direction for the user

## Your Setup (please complete the following information)

- Unity Version 2019.1.14
- XRTK Version 0.1.19

## Target Platform (please complete the following information)

- WMR immersive
- OpenVR
- HoloLens
- Lumin (Magic Leap)

## Additional context

We don't want new users confused

**Comment by StephenHodgson** [comment]
I think we ought to get more specific about our platform targets.

We now have several XR platform targets that all build on Standalone

**Comment by StephenHodgson** [comment]
Related to https://github.com/XRTK/XRTK-Core/issues/247
