### ISSUE TITLE
Clone default configuration profile on configure

### ISSUE THREAD

**Issue by StephenHodgson** [XRTK/XRTK-Core#335]
# XRTK - Mixed Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

When the XRTK is configured, we should automatically clone the default configuration profile for users. This should also fix #174 

## How would you classify your suggestion

- Usability / Configuration

**Comment by SimonDarksideJ** [comment]
In light of the "improvements" in 2019.2+ with the new asset database 2 feature, this needs escalating.

See #431
