### ISSUE TITLE
For controls that use a single axis, they are creating their config asset incorrectly

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#345]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

Post the native Oculus update, when a new config asset is created that has single axis configuration, it is incorrectly being identified as "custom" data (as used by Oculus today)

## To Reproduce

1. Create new OpenVR Controller profile
2. Examine asset to find "InputName" populated instead of "AxisX" for single axis config

## Expected behavior

Single Axis configuration should be recorded in the AxisX field

## Actual behavior

Single Axis configuration is being recorded in the custom "InputName" field

## Your Setup (please complete the following information)

- Unity Version 2019.1.14
- XRTK Version 0.1.19

## Target Platform (please complete the following information)

- WMR immersive
- OpenVR

## Additional context

Simply requires single axis configuration to provide an empty second axis

**Comment by StephenHodgson** [comment]
So the constructor is malformed?

**Comment by SimonDarksideJ** [comment]
No, the constructor is fine.  However with the requirement to have custom data for Oculus inputs, this overrides the "defaulted" approach for Axis data.  So inputs requiring axis data need to provide two axis.

I support I could also update the Axis based constructor to make the second argument not optional.

**Comment by StephenHodgson** [comment]
The constructor is definitely incorrect. Let's fix it.

**Comment by StephenHodgson** [comment]
Goes back to https://github.com/XRTK/XRTK-Core/pull/237 where we introduced the `inputName` constructors.

The constructors are ambiguous to the existing ones that have default parameters, so it's getting confused with `axisCodeX` instead of `inputName`

**Comment by StephenHodgson** [comment]
We need to update the new constructors by swapping the `inputName` with the `inputAxisType` this will help ensure we don't have ambiguity.
