### ISSUE TITLE
FR: Add dialog on XRTK-Core UPM installation, to request the install of other packages

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#351]
# XRTK - Mixed Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

Presently, when the user imports the seed package or registers the Core UPM package, they then have to manually launch the package manager to locate and install the other XRTK UPM packages.

Originally we had a dialog to select the other packages, which was very useful.  We should still have a popup on first import to offer the user the choice to import the other packages

## How would you classify your suggestion

- Usability / Configuration

## Describe the solution you'd like

When the Core package is first imported, the user should get a view asking if they want the other XRTK packages installed.

This should list the available packages for install. preferably using the Unity window launched and filtered to XRTK.  An option should exist in the menu to return to this view.

![image](https://user-images.githubusercontent.com/1793042/65422123-81767800-ddfd-11e9-9a96-57bab9f201e9.png)

## Describe alternatives you've considered

Manually registering packages

**Comment by StephenHodgson** [comment]
I wonder if there's a way to open the upm package manager window and put it a specified search.

**Comment by StephenHodgson** [comment]
Remember we used to have something like this, but we got a ton of feedback that it was annoying and took forever to install the other missing packages.

**Comment by SimonDarksideJ** [comment]
I was just investigating for a programatic way to open the UPM manager, which would be ideal.

> Remember we used to have something like this, but we got a ton of feedback that it was annoying and took forever to install the other missing packages.

The feedback wasn't that this was annoying. What was annoying was that everything was installed by default and you couldn't uninstall them (as they would just reinstall) :D

**Comment by StephenHodgson** [comment]
> I was just investigating for a programatic way to open the UPM manager, which would be ideal.

Awesome 😁 Can't wait to see it

**Comment by StephenHodgson** [comment]
Any update to this?
