### ISSUE TITLE
Camera System does not configure transparent display properly

### ISSUE THREAD

**Issue by FejZa** [XRTK/XRTK-Core#369]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

The camera system does not identify a transparent display (tested on HoloLens 1). When using the default camera config profile and building to device, the app will launch and render the skybox instead of setting the camera's clear flag to solid color black.

## To Reproduce

- Create Unity project
- Improt and configure XRTK
- Build to device

## Expected behavior

The camera configuration profile is applied.

## Actual behavior

The clear flag setting and most likely quality setting is not applied.

**Comment by StephenHodgson** [comment]
Pretty sure this is a symptom of #370

**Comment by StephenHodgson** [comment]
@FejZa any update to this?

**Comment by FejZa** [comment]
Yeah. As you said it's #370. I should have checked the camera system settings first before reporting. It did not work because the camera system checkbox was not checked.

**Comment by StephenHodgson** [comment]
We can close this then?

**Comment by FejZa** [comment]
Yes can be closed thanks.
