### ISSUE TITLE
Clone and Customize creates a new profile set instead of copying existing.

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#370]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

Clone and Customize creates a new profile set instead of copying existing.

## To Reproduce

1. Import XRTK Core & SDK in to new project
2. Click on "Mixed Reality Toolkit -> Configure"
3. Select the MixedRealityToolkit object in the hiearchy 
4. Double click in to it's configuration script
5. Click "Clone and Customize"

## Expected behavior

A new custom configuration should be generated with a copy of the existing profile set

## Actual behavior

A brand new configuration is generated with blank values

## Your Setup (please complete the following information)

- Unity Version 2019.1.1
- XRTK Version 0.1.21

## Target Platform (please complete the following information)

- N/A

## Additional context

Reported on Discord by Dino

**Comment by StephenHodgson** [comment]
I mean it's supposed to create a new one 😂

It's just not copying the values

**Comment by StephenHodgson** [comment]
[I bet we need to actually ping (select) the profile before we attempt to copy it to get the serialized values cached by the prev inspector](https://github.com/XRTK/XRTK-Core/pull/357/files#diff-bef702e6ba101bdb6c931aa1c6b7f0f8R147)
