### ISSUE TITLE
Platform configuration validation does not run

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#373]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

Originally, if the XR settings were not enabled and the Scripting runtime was anything other than IL2CPP, then XRTK prompted the user to configure it for them (or tell them to do it manually)

However, this seems to have now stopped working.

## To Reproduce

1. Create a new project
2. Import XRTK
3. Configure a scene
4. Run

## Expected behavior

At some point, a dialog should have appeared to validate the player settings to ensure XR and IL2CPP were configured.   This should also occur when the Platform is switched.

## Actual behavior

XR not checked and Mono is the new flavour of the month (default in 2019.1)

## Your Setup (please complete the following information)

- Unity Version 2019.1.14
- XRTK Version 0.1.21

## Target Platform (please complete the following information)

- Any

**Comment by StephenHodgson** [comment]
This should run as soon as you import the xrtk and it compiles successfully

**Comment by StephenHodgson** [comment]
How specifically did you import the XRTK?

- Using the package seed?
- Or manually editing the manifest?

**Comment by StephenHodgson** [comment]
I wasn't able to replicate this using the seed package

![image](https://user-images.githubusercontent.com/13334553/65985559-10177480-e450-11e9-9d6f-30ee8750f5a1.png)

**Comment by StephenHodgson** [comment]
But it did crash the editor like in #174

**Comment by StephenHodgson** [comment]
@SimonDarksideJ any update to this?

Did you use different steps than the ones I described above?

**Comment by StephenHodgson** [comment]
I'm not able to repro this.
