### ISSUE TITLE
Improve Platform support configuration to handle multiple variants correctly

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#378]
# XRTK - Mixed Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

Current Platform evaluations for services do not cover the full extent of the potential requirements, given that services require the ability to operate in the following conditions:

1. Editor Only - Service that only runs in the editor (mock) - any platform
2. Editor AND Platform - Service that only runs in the editor (mock) - specific platform
3. Platform(s) Only - Service that only runs on the platform (actual)
4. Everything - Service that is designed to work both in the editor and on any platform

Currently, only the first three modes are supported based on #374

As we expand the list of potential platforms (#377) these capabilities need to be reviewed

## How would you classify your suggestion

- Architecture / Services

## Describe the solution you'd like

(Leading from the example given in #374)

| Figure | Editor | Runtime | Description |
|---|---|---|---|
| 1 | X | | Only Editor |
| 2 | X | X | Both Editor and Runtime |
| 3 | | X | Only Runtime |
|4|X|(or) X | Everything |

1. This should run **ONLY** in the editor regardless of the target build platform but never the build:![image](https://user-images.githubusercontent.com/13334553/65984542-ff65ff00-e44d-11e9-8871-a0c34ebbab82.png)

2. This should run **ONLY** in the editor if the build target **IS** Selected:![image](https://user-images.githubusercontent.com/13334553/65984558-08ef6700-e44e-11e9-836f-0b7895db785d.png)

3. This should **never** run in the editor and only runs on the build:![image](https://user-images.githubusercontent.com/13334553/65984700-4eac2f80-e44e-11e9-955b-bb311d15ef83.png)

4. This can be run in the Editor and any build target
(Image tbc)

## Describe alternatives you've considered

No alternatives currently exist

## Additional context

Related to #377

**Comment by StephenHodgson** [comment]
We already do this sans case 4.

The 4th case could easily be handled in the service implementation.

**Comment by SimonDarksideJ** [comment]
Agreed, this is simply setting the requirement for the entire ask (so nothing gets missed in testing)

WIth 4 however, given the platform Utility is currently dictating when a service can be run, you couldn't do that in the service implementation :D But it's something to review.  Maybe by having a service define it's "supportability"

**Comment by StephenHodgson** [comment]
I am open to doing something similar to #377 though

**Comment by StephenHodgson** [comment]
> With 4 however, given the platform Utility is currently dictating when a service can be run, you couldn't do that in the service implementation

Yeah that's exactly what I was saying 😅 

You'd essentially enable the EVERYTHING flag and then in your implementation `#if/#else` out the implementation.

**Comment by StephenHodgson** [comment]
But I'm also having a hart time trying to find a use case for 4.

Could you describe it to me?

**Comment by StephenHodgson** [comment]
> 4. This can be run in the Editor when the build target is selected and can ALSO run in the Build

This just sounds like case 2.

I think it should be updated to read:

> 4. This runs in the editor all the time, and only on the selected platform build

**Comment by SimonDarksideJ** [comment]
Simply put, it meets these two conditions

* it will run in the editor if the selected build target is the same as the editor target
* it will also run in the selected target player. 

In option 2, it would only ever run in the editor for that platform and not the player. (you have a mock service for a platform)

**Comment by StephenHodgson** [comment]
> https://github.com/XRTK/XRTK-Core/issues/378#issuecomment-538009759

That's literally option 2. You lost me mate.

**Comment by StephenHodgson** [comment]
I'm not convinced we need a mock service that can't handle any platform if it's running in the editor only.

**Comment by StephenHodgson** [comment]
> it would only ever run in the editor for that platform and not the player

Is this more of what you want case 4 to be?

If we're doing a mock service for this use case why can't it be platform agnostic if it's just a mock service and use case 1?

**Comment by StephenHodgson** [comment]
| Figure | Editor | Runtime | Description |
|---|---|---|---|
| 1 | X | | Only Editor |
| 2 | X | X | Both Editor and Runtime |
| 3 | | X | Only Runtime |
|4| X |(or) X | Editor OR Runtime |

**Comment by StephenHodgson** [comment]
| Figure | Editor | Runtime | Description |
|---|---|---|---|
| 1 | X | | Only Editor |
| 2 | X | X | Both Editor and Runtime |
| 3 | | X | Only Runtime |
|4| X |(or) X | Editor OR Runtime |

**Comment by StephenHodgson** [comment]
Can I get confirmation that use case #4 is effectively `Everything` in the current dropdown?

**Comment by SimonDarksideJ** [comment]
Updated requirements

**Comment by StephenHodgson** [comment]
Can we agree that the current implementation already satisfies this issue?

**Comment by SimonDarksideJ** [comment]
The implementation discussed last night, where a service can run all the time did satisfy the requirement.
