### ISSUE TITLE
Headset location and Teleportation on Oculus resets to zero

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#392]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

Headset offset seems broken on Oculus (or may have not worked correctly), several test scenarios reset the camera height / position to either the actual floor, or after teleportation, the plane floor:

* Setting up a scene with a floor plane at 0 height, renders the camera IN the floor.  Headset height offset not applied
* Setting up a scene with the floor plane at -1 height, renders the camera above the floor. However, on teleporting, the users head position is then reset to the Plane position, no headset (starting) height applied.

So I suspect there is an issue with headset alignment / positioning with the Oculus API

Tested on both Rift and Quest

## To Reproduce

First test
1. Create a new project and configure a scene, add an Empty SceneObjects object and child Plane all at 0,0,0.
2. Run project - Observe head in floor (head and Scene at 0)

Second Test
1. Create a new project and configure a scene, add an Empty SceneObjects object and child Plane all at 0,-1,0.
2. Run project - Observe head Above floor 
3. Teleport - Now Observe head in floor (head and Scene at -1)

## Expected behavior

Head position and teleportation should operate the same as other platforms

## Actual behavior

Head position keeps falling to the floor

## Your Setup (please complete the following information)

- Unity Version 2019.1.14
- XRTK Version 0.1.23

## Target Platform (please complete the following information)

- Oculus Quest

## Additional context

Oculus Plugin still using 1.40 api, whereas 1.41 has now been released, will re-test with 1.41 and on Rift

**Comment by SimonDarksideJ** [comment]
On further investigation, this is weird.  Neither the Camera or the plane are moved. However, the Playspace height is transformed to the Teleportation location, thus rendering the camera at the same height as the teleport point.  Is this expected behaviour?

**Comment by SimonDarksideJ** [comment]
Tested in OpenVR in the same project and the playspace does not change height?
Thoughts @StephenHodgson

**Comment by StephenHodgson** [comment]
Sounds like we're not correctly calculating the difference from our start point y and our teleport location y and applying it properly.

**Comment by SimonDarksideJ** [comment]
My issue with that statement @StephenHodgson is why is it behaving differently for Oculus over other platforms, this is affecting both Windows Standalone and Android.  Yet doesn't affect devices when running openVR on the same platforms.

**Comment by StephenHodgson** [comment]
Great question. I bet it has something to do with how Unity is setting the camera position based on the XR settings or something.

**Comment by SimonDarksideJ** [comment]
Except it's altering the Playspace, not the camera?

**Comment by StephenHodgson** [comment]
> Except it's altering the Playspace, not the camera?

What is?

**Comment by SimonDarksideJ** [comment]
Resolved by #397
