### ISSUE TITLE
Cannot create new controller mapping profiles from the inspector

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#417]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

As you can see from the screenshot below, you can only assign mapping profiles in the controller mapping inspector. This is not inline with the capabilities on other areas where a profile can be selected, as each also has a "create" button

> Controller Mappings
![image](https://user-images.githubusercontent.com/1793042/70933500-01defa80-2034-11ea-8658-4a3d50226136.png)

> Input Configuration Profile
![image](https://user-images.githubusercontent.com/1793042/70933554-19b67e80-2034-11ea-93d7-86026a605a63.png)

It should be standard where a profile is required that you can create one from the inspector as well as the project view.

**Comment by StephenHodgson** [comment]
This was by design

**Comment by StephenHodgson** [comment]
There's no way to specify the type of profile you'd need because the whole list is serialized as `BaseControllerMapping` profiles

**Comment by StephenHodgson** [comment]
I think I figured out a way to do this by adding a instance type drawer dropdown, selecting the type you want to create, then pressing the "Add new mapping" button which will then create it.

**Comment by StephenHodgson** [comment]
I want to add this to 0.1.32 as well

**Comment by SimonDarksideJ** [comment]
I thought you resolved this in another PR?

**Comment by StephenHodgson** [comment]
Nope, this has it's own inspector that does specific things.

**Comment by SimonDarksideJ** [comment]
I want to add hands to 0.1.32 as well, so meh :D

**Comment by StephenHodgson** [comment]
We technically can't bc of the breaking changes in the SDK
