### ISSUE TITLE
Extend DiagnosticsSystem capabilities

### ISSUE THREAD

**Issue by FejZa** [XRTK/XRTK-Core#421]
# XRTK - Mixed Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

I'd like to extend the diagnostics system to provide settings for displaying a console-like window that will show any Debug logs and errors just as the Unity console in-game. Additionally I'd like to extend the diagnostics system settings to set a solver type for the panels positioning in space.

## How would you classify your suggestion

- Usability / Configuration
- Development Tools

**Comment by StephenHodgson** [comment]
Additionally I'd like to add:

- window should be updated from the procedurally generated one to a prefab with a concrete class that implements a `IMixedRealityDiagnosticsWindow` or something like that.

**Comment by FejZa** [comment]
Features implemented in #422
