### ISSUE TITLE
When MixedRealityControllerMappingProfile is replaced on runtime, it does not call actions from newly loaded profile, but the old one

### ISSUE THREAD

**Issue by milos12345** [XRTK/XRTK-Core#424]
Unity 2019.1.14f1
XRTK.Core 0.1.27
XRTK.SDK 0.1.17
XRTK.WindowsMixedReality 0.1.9
I have attached a project to make it clearer. 
https://drive.google.com/open?id=1uZQkLJbquFlOUh7wQSAKEp6oEgQ5LuEX
Program is supposed to have Edit mode, with all different button mapping, and Menu button should toggle these.
The XRTK in scene has `MixedRealityControllerMappingProfilesTemp`. By default it loads
`WindowsMixedRealityMotionControllerMappingProfileEditOff `which has Menu action to call EditOn action, which should turn EditMode On, and that action loads 
`WindowsMixedRealityMotionControllerMappingProfileEditOn ` profile. That works. 
But, that newly loaded profile has Menu click set to call EditOff, but instead the action that is called is again EditOn.

**Comment by StephenHodgson** [comment]
I don't believe we've setup the ability to swap out controller profiles at runtime yet.

**Comment by StephenHodgson** [comment]
See #111
