### ISSUE TITLE
Wrong actions detected if ActionsProfile names change

### ISSUE THREAD

**Issue by milos12345** [XRTK/XRTK-Core#425]
# XRTK - Mixed Reality Toolkit Bug Report

Wrong actions detected if names changed - names will be new but IDs will be from the old action.

## To Reproduce

I have removed several actions, added a few and renamed some.

## Expected behavior

There should be a way to auto regenerate IDs so the correct actions are called without the need to delete ActionsProfile and create a new one

## Actual behavior

Actions are modified in ActionsProfile, and OnInputDown will get wrong actions. The InputEventData will get new names but same IDs so comparison of received event data and the action expected will return wrong result. If I realize that one of the action in the middle is unnecessary, it seems that deleting it will mess IDs of other actions on the list.
In addition, if new profile has less number of actions, the triggering the last action on the list will result in ~index out of bounds logged into console

## Your Setup (please complete the following information)

- Unity Version 2019.1.14f1
- XRTK Version 0.1.27

## Target Platform (please complete the following information)

- WMR immersive

**Comment by StephenHodgson** [comment]
Swapping the input actions from another configuration is not supported yet. 

See #379
