### ISSUE TITLE
XRTK on OpenUPM

### ISSUE THREAD

**Issue by favoyang** [XRTK/XRTK-Core#427]
Hi @XRTK devs,

Thanks for creating the amazing project. I'm the creator of [OpenUPM](https://openupm.com), a public upm registry with automatic build pipelines that publish new package bundle based on valid git tags. You can read [the announcement](https://www.patreon.com/posts/openupm-beta-is-32544176) to get the basic idea, so far it hosts 80+ packages as of December 2019.

I have included the package to the service.
https://openupm.com/packages/com.xrtk.core/

If you feel interesting, you can also explore to [add a badge](https://openupm.com/docs/adding-badge.html) to README:

[![openupm](https://img.shields.io/npm/v/com.xrtk.core?label=openupm&registry_uri=https://package.openupm.com)](https://openupm.com/packages/com.xrtk.core/)

I've noticed that there're already many package delivery options available there, including a custom registry. It's totally okay to ignore this and close the issue.

**Comment by StephenHodgson** [comment]
@favoyang thank you so much for bringing this up to our attention :)

I'll take a look and see what it'll take add our packages there.

**Comment by favoyang** [comment]
Thanks for accepting the feature request. I've added other your upm packages to the OpenUPM platform.

- https://openupm.com/packages/com.xrtk.lumin/
- https://openupm.com/packages/com.xrtk.oculus/
- https://openupm.com/packages/com.xrtk.sdk/
- https://openupm.com/packages/com.xrtk.wmr/

Please notice that mentioning OpenUPM or adding the badges to README are totally optional. In case you're okay with what we have so far, feel free to close the issue.

Happy new year.

**Comment by StephenHodgson** [comment]
We'll be sure to add it to our documentation and site it as an option in the release.

I would like to sync up on how to push releases to the platform via our build pipeline. Ping me and @SimonDarksideJ there?

Thanks

**Comment by favoyang** [comment]
@StephenHodgson and @SimonDarksideJ You don't need to manually push releases to the OpenUPM platform. The service watches your GitHub releases, find all new git tags that are valid semver (x.y.z or v.x.y.z), and publish new package for you. In another word, it works in a pull mode rather than a push mode. You can click on any links I mentioned in the thread, i.e. [com.xrtk.lumin/](https://openupm.com/packages/com.xrtk.lumin/), navigate to the _version history_ section, you will notice that all existing versions are built successfully.

AFAIK, it works perfectly so far. One exception is that if a repository do need a very custom build script, then it may be not suitable for the OpenUPM (or we need a new feature to support that). But it unlikely for all XRTK sub-projects - you already offer installing via git, and the OpenUPM build are equal to the git release.

Let me know whether my explanation is clear.

**Comment by StephenHodgson** [comment]
I'll let you know if we happen to add Danny additional modules. 

Should be good then. I'll leave this open until we add the open upm links to all the documentation.

**Comment by StephenHodgson** [comment]
Before we close this, let's be sure to add the open upm badge to our readme
