### ISSUE TITLE
Default Profiles - Configuration Issues Collection

### ISSUE THREAD

**Issue by FejZa** [XRTK/XRTK-Core#431]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

I noticed some minor configuration issues in the default profile, that need to be fixed. Collecting them here as I find them.

- `DefaultMixedRealityControllerMappingProfile` contains an empty entry in the mapping definitions list
- `DefaultNativeOculusTouchControllerMappingProfile` is not marked as a default profile (isCustomProfile: 0)

## Screenshots

![mapping_profile](https://user-images.githubusercontent.com/9565734/71767015-3513fb80-2f07-11ea-969e-7fa35d19a36a.PNG)
![mapping_profile_2](https://user-images.githubusercontent.com/9565734/71767016-37765580-2f07-11ea-8b19-2cba6b3a3050.PNG)

**Comment by SimonDarksideJ** [comment]
OK, in short this is a side effect of the new asset database.
In 2019.1 and previous, assets were imported but not evaluated until they were first accessed.
In 2019.2+ with the new asset database 2, it seems all assets are evaluated once they are imported.

The effect on this is that if you import the SDK first and it contains GUID's to dependant assets (e.g. the Native Oculus Touch controller mapping) that cannot be resolved, the asset system now corrupts that reference.  Such that even after the dependent asset has been imported, the original GUID's are lost and the link is broken.

To resolve this, I propose we remove all references to dependant configuration located in other UPM packages by default, then add a routine in the dependancies that once they are imported, you are prompted if you would like to add the default configuration to your current configuration for that package.

E.G.
* When you import the SDK package, it will only reference packages in Core.
* If you then import the Lumin package, it will prompt to add Lumin scriptable config
* If you import the Oculus package, it will prompt to add the default Oculus controller mappings

**Comment by StephenHodgson** [comment]
I feel like we should open a bug report with Unity to make sure that's the intended behavior or if it's a regression.

**Comment by SimonDarksideJ** [comment]
It's likely by design, with the Asset Database V2, they have simply gotten more stringent about reference issues.  Like with the asmdef links, it used to be that unresolved links were ignored, now they are a hard error.

We just need to update to ensure that dependant UPM packages manage their own config, which is what #433 is about

**Comment by StephenHodgson** [comment]
Well let's file the bug and get a definitive answer.

**Comment by Jarodshow** [comment]
[Unity has a struct for this kind of behavior](https://docs.unity3d.com/2019.3/Documentation/ScriptReference/LazyLoadReference_1.html)

**Comment by StephenHodgson** [comment]
Nice find @Jarodshow

**Comment by StephenHodgson** [comment]
Now how do we actually use it? lol

**Comment by SimonDarksideJ** [comment]
Fix applied for Oculus in development, waiting for new core release to test and then rollout.

Process is like this:
* No non-core profiles in SDK
* When a new platform is loaded, it checks if configuration has been added
* If not, it warns the user and asks them to add config (e.g. Controller Mapping)

Config has to be assigned manually as Unity does not provide a way to access defaults in a package.

**Comment by StephenHodgson** [comment]
I think we should move the platform specific default profiles into their respective submodules and reorganize the subodule projects to include a `DefaultProfiles` folder and a `Scripts` folder.

**Comment by StephenHodgson** [comment]
See https://github.com/XRTK/SDK/pull/118

**Comment by SimonDarksideJ** [comment]
Platform specific profiles should be located IN the platform, which is what XRTK/Oculus#41 is all about.
Once complete, this will be rolled out to other platforms (when things quiet down a bit :D )

**Comment by StephenHodgson** [comment]
Yeah let's def focus on this after the controller mapping refactor so we don't have to do a bunch of extra work. We'll have to re-create most of the profiles anyway for it

**Comment by StephenHodgson** [comment]
We can coordinate this change with that work as well.
