### ISSUE TITLE
Add Focus Testing

### ISSUE THREAD

**Issue by StephenHodgson** [XRTK/XRTK-Core#45]
Port some of the initial HTK focus tests to ensure focusing works properly

**Comment by wassx** [comment]
Is this related to world space UI sorting?

**Comment by StephenHodgson** [comment]
Yes, part of it, but we also want to be doing validations for all our focusing that we used to do in the old HoloToolkit

**Comment by StephenHodgson** [comment]
I'm not convinced 2e really need this anymore
