### ISSUE TITLE
When an empty Registered Service Provider is added, a warning / error is logged

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#466]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

When an empty Registered Service Provider is added, a warning / error is logged.
Ideally, this should ignore providers not yet configured with an instance type

## To Reproduce

1. Create project with XRTK
2. Clone and create new Registered Service Providers config profile
3. Add a new profile, but leave fields blank

## Expected behavior

Registered services providers with no instance type configured should be ignored

## Actual behavior

The following error is spammed to the consul multiple times

```
Could not load the New Configuration 0 configuration's InstancedType.
UnityEngine.Debug:LogWarning(Object)
XRTK.Services.MixedRealityToolkit:RegisterServices(MixedRealityServiceConfiguration`1[]) (at Packages/com.xrtk.core/Services/MixedRealityToolkit.cs:713)
XRTK.Services.MixedRealityToolkit:InitializeServiceLocator() (at Packages/com.xrtk.core/Services/MixedRealityToolkit.cs:455)
XRTK.Services.MixedRealityToolkit:ResetConfiguration(MixedRealityToolkitConfigurationProfile) (at Packages/com.xrtk.core/Services/MixedRealityToolkit.cs:121)
XRTK.Inspectors.MixedRealityToolkitInspector:<OnInspectorGUI>b__4_1() (at Packages/com.xrtk.core/Inspectors/MixedRealityToolkitInspector.cs:103)
UnityEditor.EditorApplication:Internal_CallDelayFunctions()
```

## Your Setup (please complete the following information)

- Unity Version  2019.1.14
- XRTK Version development

**Comment by StephenHodgson** [comment]
Duplicate?

If not we need to address this in the Configuration Refactor #455

**Comment by StephenHodgson** [comment]
But this makes sense if there's no type defined, no not really a bug.  It just needs to not try to initialize it.
