### ISSUE TITLE
Camera System | DefaultHeadHeight setting not implemented

### ISSUE THREAD

**Issue by FejZa** [XRTK/XRTK-Core#487]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the enhancement

The camera profile defines a setting `DefaultHeadHeight` that states "The default head height the rig will start at if a platform doesn't automatically adjust the height for you.".

That setting, while it exists, is not used anywhere. The `MixedRealityCameraSystem` defines a property `DefaultHeadHeight` and will apply the setting to it in the constructor

```
public MixedRealityCameraSystem(MixedRealityCameraProfile profile)
            : base(profile)
        {
            this.profile = profile;
            DefaultHeadHeight = profile.DefaultHeadHeight;

            if (profile.CameraRigType.Type == null)
            {
                throw new Exception("Camera rig type cannot be null!");
            }
        }
```

but apart from that the value is not referenced anywhere anymore and does not provide any functionality.

## To Reproduce

Follow references to the setting in Visual Studio.

## Expected behavior

The setting is respected and applied when the application starts.

**Editor**

In the editor the tracked pose driver won't do anything unless a device is attached. So for the editor there is two scenarios:

- Editor & No Device connected: The `DefaultHeadHeight` sets the main camera Y position.
- Editor & Device connected: The `DefaultHeadHeight` sets the tracked pose driver origin `CameraRig.CameraPoseDriver.originPose = new Pose(new Vector3(0f, headHeight, 0f), Quaternion.identity);`. Essentially HeadHeight shoudl be set to `DefaultHeadHeight` on init.

**Platform build**

The `DefaultHeadHeight` sets the tracked pose driver origin `CameraRig.CameraPoseDriver.originPose = new Pose(new Vector3(0f, headHeight, 0f), Quaternion.identity);`. Essentially HeadHeight shoudl be set to `DefaultHeadHeight` on init.

## Actual behavior

Nothing.

**Comment by StephenHodgson** [comment]
Not really a bug. Just not implemented.

**Comment by StephenHodgson** [comment]
Probably best to move this issue to the platform(s) repo's that you're having trouble on.

**Comment by FejZa** [comment]
If a setting exists and indicates it does something but it doesn't, it's kinda a bug. I am having trouble in the editor with it. The implementation that needs to be made here is not specific to any platform.

**Comment by FejZa** [comment]
I can take a look at this.

**Comment by StephenHodgson** [comment]
I think we always want the camera to start at the origin. So any platforms that move the head up and away will need to have the playspace moved down in the same amount it was offset from the beginning.

**Comment by StephenHodgson** [comment]
In the future, I was thinking about adding start location markers that will initialize the camera rig at the origin, then move the playspace to the start location marker.

**Comment by FejZa** [comment]
I don't think I understand. That sounds like something that would work, if everything in the scene is parented to the `MixedRealityPlaypace`. But not going to work if my environment is a sibling to it.

**Comment by StephenHodgson** [comment]
Whoa there, nothing should be parented under the playspace unless it's part of the user's local coordinate system.

**Comment by FejZa** [comment]
Right. So how does what you said above relate to this issue then?

**Comment by StephenHodgson** [comment]
I just wanted the desired behaviour to be clear

**Comment by FejZa** [comment]
I know, I am just not getting it. Essentialls, say I have a "Floor" at (0,0,0).
Currently when playing my camera (head) will also be at (0,0,0). This is the problem I am trying to solve here.

**Comment by StephenHodgson** [comment]
Really the problem we're solving here is that each platform starts the camera at different places and we want the user's head position relative to the playspace to be consistent. 

The playspace is at the user's feet

**Comment by StephenHodgson** [comment]
Yup, it sounds like we just need to have the camera be moved up relative to the playspace, then the playspace moved down the same amount we moved the camera up relative to the scene root.

**Comment by StephenHodgson** [comment]
Although tbh just to make it easier we ought to just move up any camera's that don't move and not worry about moving the playspace back down

**Comment by FejZa** [comment]
If I move the camera 1.7m up and the playspace (where my feet are) 1.7m down. I end up being 2.4m tall. Isn't that wrong?

**Comment by StephenHodgson** [comment]
depends on how you move it according to the frame of reference. One is relative to the playspace and the other is relative to the world.

**Comment by SimonDarksideJ** [comment]
This also depends on:

a) if Unity already moves the head (WMR VR, Steam/OpenVR)
b) if a platform has been enabled to move the head (Oculus)
c) if a platform head height is never touched (HL1/HL2/ML)

**Comment by FejZa** [comment]
What do you mean by c? HL1/HL2 do move the head / camera transform.

**Comment by SimonDarksideJ** [comment]
I was under the impression that even from the HTK days, that the starting head position was 0,0,0 for HL1/HL2, meaning you had to adjust the camera height before launch.  Happy to have that preconception altered.

**Comment by StephenHodgson** [comment]
I believe it's post launch
