### ISSUE TITLE
Do not report "No configuration needed" when configuration is not needed, it wastes valuable screen space

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#492]
# XRTK - Mixed Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

It is too excessive to paint "No configuration needed" next to profiles / services / configuration when it is not required.  Just don't put anything.

![image](https://user-images.githubusercontent.com/1793042/78383011-9d8a7b80-75cf-11ea-994d-8f86245eef09.png)

Only have the field for configuration if it is REQUIRED.

## How would you classify your suggestion

- Usability / Configuration

**Comment by StephenHodgson** [comment]
What I'd really like it for each element to be a fold out

**Comment by StephenHodgson** [comment]
When I'm done with #494 then profiles will be required for controller data providers
