### ISSUE TITLE
Teleporting does not land on desired landing location

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#504]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

Currently, when a user teleports to a location, their landing spot is not where they selected, for example

![image](https://user-images.githubusercontent.com/1793042/78596630-0843ed00-7844-11ea-932a-7b0e2668b0cd.png)

1. User in left area selects a teleport location
2. User lands in a space "relative" to where they selected, as shown on right (different based on teleport direction)

GIF of this happening in the editor
![Development-TeleportationBroken-2](https://user-images.githubusercontent.com/1793042/78596502-d03caa00-7843-11ea-9aef-c820ee117635.gif)

## To Reproduce

1. Create project and configure
2. Add floor to teleport on
3. Teleport to an obvious location, e.g. Corner
4. Observe landing location

Additional replication

1. Create project and configure
2. Add floor to teleport on
3. Add a new plane, size to a small square and apply a red material
4. Add "Teleport Hostspot" SDK component
5. Teleport to HotSpot
4. Observe landing location

## Expected behavior

Teleport should land where they selected

## Additional notes
Teleport system is a mess :D  and needs an overhaul.  Could not assign the teleport activity to a button.  Post 0.2 change to teleport system.

**Comment by StephenHodgson** [comment]
What platform were you testing this out on?

**Comment by SimonDarksideJ** [comment]
ALL of them. Primarily WMR, Oculus and OpenVR

**Comment by StephenHodgson** [comment]
Works correctly on Lumin last I checked. I wonder if it's updating the position even though you've let go and continued to move your hand?

**Comment by StephenHodgson** [comment]
I did make some changes in #517 to the Teleport system to ensure we're at least using the [correct height](https://github.com/XRTK/XRTK-Core/pull/517/files?file-filters%5B%5D=.cs#diff-b63a3759cb94eba085c6d2e4e4a0d699R224)

**Comment by SimonDarksideJ** [comment]
There is a possibility that the movement is picking up / changing based on the letting go of the thumbstick, but no matter how careful I am, it does.
Might try changing the teleport action to a button to verify.

But ultimately, this shouldn't happen, the place the pointer is when you let go should be the location you land.

**Comment by StephenHodgson** [comment]
Yeah I think some verification tests should do the trick. 

I was thinking about putting a small sphere in the place the user lets go and the pointer position recorded. Then once the teleport is finished looking down to see how close you came.

**Comment by SimonDarksideJ** [comment]
As you can see in the video, sometimes quite far away, orientation seems to matter and direction.
The landing offset does seem exponential

**Comment by StephenHodgson** [comment]
One possibility is that we're using the wrong frame of reference to do our calculations from. 

Maybe using a world space position instead of a local one or vice versa?

**Comment by StephenHodgson** [comment]
I bet it's this line:

```
cameraParent.RotateAround(cameraPosition, Vector3.up, targetRotation.y - cameraTransform.eulerAngles.y);
```

**Comment by SimonDarksideJ** [comment]
In most cases, I'm not rotating when I teleport to replicate the issue. But I'm firing up to test with the Camera system PR
Surely the "target" should be where the raycast collides with the surface?

**Comment by SimonDarksideJ** [comment]
Updated the issue log @StephenHodgson , used a hotspot as the target and differentiation is clearer.

User should at least land in the hotspot zone, but no.  make sure you test from different angles

**Comment by FejZa** [comment]
I am picking this up
