### ISSUE TITLE
Replace XRTK custom shaders with Unity's built-in shaders

### ISSUE THREAD

**Issue by FejZa** [XRTK/XRTK-Core#533]
# XRTK - Mixed Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

I'd like to remove any custom shaders used in XRTK and replace them with Unity's built-in shaders.
This is a step in anticipation for XRTK's URP/HDRP support. Removing custom shaders will help in transitioning the toolkit to render pipelines. There shouldn't be any breaking changes here.

## How would you classify your suggestion

- New platform support

## Describe the solution you'd like

Remove all custom shaders so that materials can automatically be migrated to render pipelines.

**Comment by StephenHodgson** [comment]
Isn't this just a duplicate (or part of a step for) #407 ?

**Comment by FejZa** [comment]
It's definitely a step towards #407

**Comment by StephenHodgson** [comment]
Can we close this one and just use #407 as our task list?

**Comment by FejZa** [comment]
Okay, we can do that.
