### ISSUE TITLE
Opening the Controller popouts from the Data Providers list causes an NRE

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#553]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

Opening the Controller popouts from the Data Providers list causes an NRE
The popout window also does not open.

## To Reproduce

1. Open Unity on the Dev branch
2. Create a scene with the toolkit configured, or open the Base Scene
3. Select the MRT GO
4. Open the Input settings configuration (DefaultMixedRealityInputSystemProfile)
5. Expand the Data providers foldout
6. Open the OpenVR controller data provider config (OpenVRControllerDataProviderProfile)
7. Click on ANY of the simple configuration popouts

## Expected behavior

Controller popout should appear and allow configuration

## Actual behavior

NRE reported in Editor console, no popout

```
NullReferenceException: Object reference not set to an instance of an object
UnityEditor.EditorWindow.Close () (at C:/buildslave/unity/build/Editor/Mono/EditorWindow.cs:927)
XRTK.Editor.ControllerPopupWindow.Show (XRTK.Definitions.Controllers.MixedRealityControllerMappingProfile profile, UnityEditor.SerializedProperty interactionMappingProfiles) (at Packages/com.xrtk.core/Editor/ControllerPopupWindow.cs:86)
XRTK.Editor.Profiles.InputSystem.Controllers.BaseMixedRealityControllerDataProviderProfileInspector+<>c__DisplayClass15_0.<RenderControllerMappingButton>b__0 () (at Packages/com.xrtk.core/Editor/Profiles/InputSystem/Controllers/BaseMixedRealityControllerDataProviderProfileInspector.cs:283)
UnityEditor.EditorApplication.Internal_CallDelayFunctions () (at C:/buildslave/unity/build/Editor/Mono/EditorApplication.cs:209)
```

## Your Setup (please complete the following information)

- Unity Version 2019.1.14
- XRTK Version 0.2.0 (dev)

**Comment by StephenHodgson** [comment]
Pretty sure I thought I fixed this in #551

**Comment by StephenHodgson** [comment]
It's because I moved the path finder up a level into the Runtime folder and [the controller popout window controller json data is in an editor folder](https://github.com/XRTK/XRTK-Core/pull/551/files?file-filters%5B%5D=.cs#diff-3116421da0484b3bfc052913f106fc22R68).

**Comment by StephenHodgson** [comment]
I don't understand how by the time we check if the window is null on the prev line, it becomes null when we go to close it

**Comment by StephenHodgson** [comment]
![image](https://user-images.githubusercontent.com/13334553/80523459-24770d80-895c-11ea-933a-a1076d88e8bc.png)

**Comment by SimonDarksideJ** [comment]
Different issue Stephen, RTFI

Your issue was with the Controller mapping FOLDOUT. this is to do with the Controller POPOUT from within the Data Provider config that @FejZa added recently.

As noted, your issue was fixed in your PR, this issue existed in DEV

**Comment by StephenHodgson** [comment]
That's what I'm talking about. It's the source of the NRE

**Comment by SimonDarksideJ** [comment]
Ahh, I see. SO you believe we have a fix?

**Comment by StephenHodgson** [comment]
it's not fixed. 😭

**Comment by StephenHodgson** [comment]
Turns out one of the instance type references was broken.
