### ISSUE TITLE
"Missing profile for Windows Mixed Reality Spatial Mesh Observer" reported in project

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#62]
## Describe the bug
Whether one is configured or not, the following error keeps appearing in an XRTK project
"Missing profile for Windows Mixed Reality Spatial Mesh Observer"

Unknown as to the cause at this time

## To Reproduce
1. Open an XRTK project
2. do "stuff" :S 

## Expected behavior
No errors from the toolkit being in the project... ever

## Information(please complete the following information):
 - Version: [e.g. 2018.3.1f1]
- Release or Commit sha: [e.g. Latest Release]

## Additional context
Unknown if this is related to #57 as the error was showing up mainly there in testing

**Comment by StephenHodgson** [comment]
After closing and opening the project and a new scene, were you still getting this error?
