### ISSUE TITLE
Using "Configure" causes Assert fail errors

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#628]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

When opening the development branch clean and using the "Mixed Reality Toolkit-> Configure" option, the console gets flooded with 7 errors, as follows

```
Assertion failed
UnityEngine.Debug:Assert(Boolean)
XRTK.Editor.PropertyDrawers.MixedRealityProfilePropertyDrawer:OnGUI(Rect, SerializedProperty, GUIContent) (at Packages/com.xrtk.core/Editor/PropertyDrawers/MixedRealityProfilePropertyDrawer.cs:120)
UnityEditor.EditorGUILayout:PropertyField(SerializedProperty, GUIContent, GUILayoutOption[])
XRTK.Editor.Profiles.MixedRealityToolkitRootProfileInspector:RenderSystemFields() (at Packages/com.xrtk.core/Editor/Profiles/MixedRealityToolkitRootProfileInspector.cs:180)
XRTK.Editor.MixedRealityToolkitInspector:OnInspectorGUI() (at Packages/com.xrtk.core/Editor/MixedRealityToolkitInspector.cs:135)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

```

This source down to 
> Line 120 of "Core/Editor/PropertyDrawers/MixedRealityProfilePropertyDrawer.cs"

## To Reproduce

1. Checkout dev clean
2. Open Unity
3. Hit "Mixed Reality Toolkit-> Configure"

**Comment by StephenHodgson** [comment]
7 errors? probably one for each service we're attempting to render fields for in the root inspector. I'll check it out.

**Comment by StephenHodgson** [comment]
I wasn't able to repro with the steps you provided. Was there any additional steps you may have omitted?

DId you select anything or have any specific scene open when configuring?

Does this happen in brand new projects, or just the core project when doing a fresh clone and pressing configure?

**Comment by StephenHodgson** [comment]
@SimonDarksideJ any update to this? Are you still running into this issue?

**Comment by StephenHodgson** [comment]
Wasn't able to repro this in latest 2019.4.15f1 release and core/sdk preview packages
