### ISSUE TITLE
OnPointerUp(...) raised right after OnInputDown(...) even though the button is still pressed

### ISSUE THREAD

**Issue by FejZa** [XRTK/XRTK-Core#647]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

When pressing a button on a controller, e.g. Oculus Touch controller, the input event `OnPointerDown(...)` is raised and instantly right after it `OnPointerUp(...)`. This is happening even if the button is being pressed and hold.

## To Reproduce

> 

1. Create a Canvas with a UI Selectable like a button
2. Use controllers to press the created button and hold down the trigger
3. Observe how the button changes state to "pressed" state but releases right away back to normal

> 

1. Create a scene with an object with `ManipulationHandler` attached
2. Try selecting the object for manipulation
3. Observe nothing happens since the select action is released right away

## Expected behavior

The input up event is only raised when the input source is actually up.

## Actual behavior

Press and hold / Click and hold does not work.

## Your Setup

- Unity Version 2019.1.14f1
- XRTK Version 0.2.0

**Comment by SimonDarksideJ** [comment]
This has been fixed on Oculus with https://github.com/XRTK/Oculus/pull/96
Need to verify on WMR to complete

**Comment by FejZa** [comment]
Tested and verified this did not affect WMR, seems to have been an Oculus specific issue. I was also always using Oculus when I ran into this. WMR works fine.
