### ISSUE TITLE
Feature Request: Runtime APIs to get the version of each XRTK module in use

### ISSUE THREAD

**Issue by FejZa** [XRTK/XRTK-Core#648]
# XRTK - Mixed Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

For testing and debugging as well informative purposes there should be a convenient way for developers to get the version in use for each XRTK module active when the application is running, e.g.

XRTK.Core v0.2.0
XRTK.SDK v0.2.0
...

## How would you classify your suggestion

- Usability / Configuration
- Dev Tools

## Describe the solution you'd like

I can imagine this being an API of `MixedRealityToolkit` itself, e.g.

`public string[] MixedRealityToolkit.Versions { get; private set; }`

**Comment by StephenHodgson** [comment]
I wonder if there's a way to get this from the Unity package APIs

**Comment by StephenHodgson** [comment]
@FejZa I was doing some research into this. We should be able to set the assembly version based on the asmdef. I'll see if we can automate this somehow.
