### ISSUE TITLE
After installing the 0.2 preview SDK only, Option to select other packages in the menu is missing

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#663]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

Installed the 0.2 preview, which includes the new dialog for quickly installing the other XRTK packages, however, after install the menu option to select packages is missing

## To Reproduce

1. Create new project
2. Install XRTK
3. Observer package selection window and unselect everything except SDK
4. Finish install
5. Open Editor menu

## Expected behavior

Menu option to view and install other packages

## Actual behavior

Nope, nothing, nada

## Screenshots
Current
![image](https://user-images.githubusercontent.com/1793042/92478489-225e6e80-f1da-11ea-94df-959768febe1e.png)

Should include
![image](https://user-images.githubusercontent.com/1793042/92479761-e0362c80-f1db-11ea-9d95-540cbd6d76ad.png)

## Your Setup

- Operation system: Windows
- Unity Version: 2019.1.14f0
- XRTK Version: 0.2.0-preview (UPM)

**Comment by StephenHodgson** [comment]
I'm surprised it's still there in the menu. After the initial installation the menu item should have been removed, and devs use the native package manager to grab any additional packages they require.

**Comment by StephenHodgson** [comment]
This is by design. Installing additional packages via the upm window is the only way to get additional packages after the initial installation. The menu was added I case the upm server was somehow unreachable or if there was a compilation error on seed package import.
