### ISSUE TITLE
Configuration profiles for NON-SDK packages do not seem to import correctly

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#664]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

If you install the Core + SDK, the asset GUID regeneration for the assets in the "XRTK.Generated" folder seem to work fine, However.

For the ancillary packages, Oculus, WMR, Lumin, the guide regeneration / realignment does not seem to go deep enough and the input actions configuration for each controller still maps to the GUID's for the original assets

## To Reproduce

1. Create a new XRTK project
2. Import XRTK and SDK (0.2 Preview packages)
3. Check controller configuration is as expected (see image 1 below)
4. Import another package (Oculus)
5. Accept prompt for importing the config
6. Check controller configuration (see image 2)

On inspection:

* The GUID's for the SDK assets are different, checking the controller action mapping asset for an OpenVR controller confirms the GUID's are different (regeneration successful)

* The GUID's for the Oculus assets have NOT been regenerated, checking the controller action mapping asset for an OpenVR controller confirms the GUID's are IDENTICAL

## Expected behavior

Guids in the "copied" assets should have new GUID's and have the lookups reflected in the assets they are used, as happens with the SDK assets
com.xrtk.sdk - OpenVRControllerDataProvider - controllerMappingProfiles -> XRTK.Generated - OpenVRControllerDataProvider - controllerMappingProfiles (working)

GUID's for controller mapping profiles different

## Actual behavior

com.xrtk.oculus - LeftOculusTouchControllerDataProvider - controllerMappingProfiles -> XRTK.Generated - LeftOculusTouchControllerDataProvider - controllerMappingProfiles (NOT working)

GUID's for controller mapping profiles identical

## Your Setup

- Operation system Windows
- Unity Version 2019.1.14f0
- XRTK Version 0.2.0-preview

**Comment by StephenHodgson** [comment]
Try installing the sdk last. I think it might be because the guid regenerator is expecting the old guid references but they're technically invalid because the old references have already been rewritten.

**Comment by SimonDarksideJ** [comment]
That seems to make the opposite of sense @StephenHodgson , as why would the SDK effect when a different package is installed?
The SDK installs one as it's GUID's are regenerated correctly.

My initial suspicion is that the GUID regeneration isn't going deep enough, seeing it does seem to update the higher levels (, Input Actions, Speech, Controller data provider, etc)  but the lowest level isn't

**Comment by StephenHodgson** [comment]
It's based on the root folder we provide it.

It makes sense if you're installing step by step and not all at once.

**Comment by StephenHodgson** [comment]
I think the root of the problem is that the packages aren't being installed all at once.

If you install one package, then re-generate the guids, when you go to install the next package, the guid references are already changed, and there is a mismatch.

**Comment by SimonDarksideJ** [comment]
OK, issue resolved or at least diagnosed.
Seems when the profiles were stripped and moved to their own packages, some of them (namely WMR and Oculus) were still sharing the mappings from the OpenVR implementation and hence did not have their own input mappings.

Hence when the profiles that WERE in the packages were copied, they worked. 

The simple solution for now is to create/copy the input mapping profiles to the respective packages.  The new GUID regen system isn't up to "sharing" config across packages atm.

**Comment by SimonDarksideJ** [comment]
Added copies of the original assets to the respective packages.

Guid's should not conflict as they are regenerated when they are copied to the users XRTK.Generated folder.  Tested by removing the XRTK.Generated folder and forcing a reimport.
