### ISSUE TITLE
Update docs to show how to define scoped registries in 2019.4.12f1+

### ISSUE THREAD

**Issue by StephenHodgson** [XRTK/XRTK-Core#674]
Once we move to 2019.4 LTS we'll likely lock onto a version older than 12f1, which introduced the ability to define scoped registries in the project settings in the Unity editor itself. We should add this to the getting started and downloading documentation.

**Comment by SimonDarksideJ** [comment]
I'll pick this up this weekend, now that we have moved to 2019.4

**Comment by StephenHodgson** [comment]
![image](https://user-images.githubusercontent.com/13334553/100490681-f4e6da00-30d1-11eb-89f4-4904114f3989.png)
