### ISSUE TITLE
0.2-Preview - Platform Configuration issues

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#675]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

Configuration profiles are initialised without a Runtime platform configured

![image](https://user-images.githubusercontent.com/1793042/97361356-4f083b80-1897-11eb-9e05-ac82107fb6ef.png)

## To Reproduce

1. Create a new project
2. Import XRTK
3. Configure XRTK

## Expected behavior

All default profiles should work "out of the box"

## Actual behavior

No Platform drop downs are configured.

## Your Setup

- Operation system [e.g. windows, macos, linux]
- Unity Version [e.g. 2019.1.14f0]
- XRTK Version [e.g. 0.2.0]
- XRTK Commit SHA [e.g. 0b40524df4b67fd3bdf305185d5426213040b43f]

**Comment by SimonDarksideJ** [comment]
Checking other "Platform" configuration, same result. Seems the Platform selection is broken or unresolved in a clean project

**Comment by StephenHodgson** [comment]
@FejZa @SimonDarksideJ did this get fixed with our profile changes in the submodules?

**Comment by StephenHodgson** [comment]
Cannot repro with latest previews. Open again if issue still persists
