### ISSUE TITLE
Add a platform independent way to validate if the runtime client has internet access

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#682]
# XRTK - Mixed Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

There should be a simple single flag/property/method to query the XRTK to check if there is a valid internet connection, regardless of which platform the project is running on.

Ideally, this should integrate with the Platform system to give a single point of call.

## How would you classify your suggestion

- New platform support
- Usability / Configuration
- Architecture / Services

## Describe the solution you'd like

A single property/field/method against the Platforms interface with a single call that is served by the currently active platform.

**Comment by StephenHodgson** [comment]
I would assume this would be a flag in the networking system

**Comment by SimonDarksideJ** [comment]
I would agree, yes
