### ISSUE TITLE
Cannot assign Tracked Hand poses to Simulated Hand Data Provider

### ISSUE THREAD

**Issue by StephenHodgson** [XRTK/XRTK-Core#691]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

Unable to assign tracked hand poses to the Simulated Hand Data provider profile

## To Reproduce

1. Create a new project
2. Import the com.xrtk.core and com.xrtk.sdk packages
3. Configure the xrtk
4. See error: `Failed to register the SimulatedHandControllerDataProvider service: UnityEngine.MissingReferenceException - The variable data of HandControllerPoseProfile doesn't exist anymore.`
5. Select the `Assets\XRTK.Generated\SDK\Profiles\Input\DataProviders\HandControllers\Simulated\SimulatedHandControllerDataProviderProfile` asset in the project window
6. Scroll down and open the **Simulated Hand Tracking Settings** fold out
7. Open the **Tracked Poses** foldout
8. If the array has 0 elements, then add 5 to the size
8. Observe the broken element list

## Screenshots

![image](https://user-images.githubusercontent.com/13334553/99927975-1aec3300-2cfc-11eb-9dbe-0ea09c26dad2.png)

## Your Setup

- Unity Version 2019.4.15f1
- XRTK Versions:
  - com.xrtk.core@0.2.0-preview.120
  - com.xrtk.sdk@0.2.0-preview.23
- XRTK Commit SHA 10166a6ffa4d02a433acc81b8817450b19422299

**Comment by FejZa** [comment]
It's so weird that I am not running into this issue and was never able to reproduce
