### ISSUE TITLE
Prompt user to install SDK if no configurations found

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#702]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

For the 0.2 release, it is still expected that most new users will need to have the SDK installed.  So the user should be warned if they try to configure their project "Mixed Reality Toolkit Configure" without any valid configurations available in the project.

## To Reproduce

1. Create a new project with just the XRTK and 1 platform. No SDK
2. Configure the starting scene

## Expected behavior

* If no valid configurations are present, warn the user on clicking configure
* If no valid configurations present and the user selects the `MixedRealityToolkit` Gameobject, throw a warning
* If no valid configurations present and the user selects a `MixedRealityToolkitRootConfiguration` file, throw a warning
* If no valid camera data provider is configured for the current build platform, throw a warning

**Comment by StephenHodgson** [comment]
I think this is missing a few key details. 

Configuration will fail if a camera data provider isn't found, correct?

So if there aren't any services or data providers available, then I think we ought to cancel the configuration and prompt the user to install the sdk package from the unity package manager.

**Comment by StephenHodgson** [comment]
> For the 0.2 release, it is still expected for the user to have the SDK installed. 

for most users sure, I think the real language here should be "Valid configurations are expected to be present when configuring"

**Comment by SimonDarksideJ** [comment]
FYI, this was Core only (plus a platform) and I configured the Camera and Input system using the systems contained in the Core.  No actual SDK parts were needed.

But I agree, SDK is mandatory for 0.2. All food for thought later.

**Comment by StephenHodgson** [comment]
I never said the SDK was mandatory, Just highly encouraged for new developers.

**Comment by StephenHodgson** [comment]
Also testing platforms without the sdk isn't part of our test plans. Let's try to clarify that when tested releases it's expected to be testing with the sdk.
