### ISSUE TITLE
Update Teleport System to allow any input to begin and complete a teleport sequence

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#721]
# XRTK - Mixed Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

Currently, the teleport system is locked to using a Vector 2 input (touchpad / thumbstick) for teleporting, a remnant of starting from WMR.

This is far too limiting as on some platforms and projects alternate input would be preferred for initiating/completing or canceling a teleport sequence. The only way to achieve this today would be to write an alternate Teleport handler.

## How would you classify your suggestion

- Usability / Configuration
- Architecture / Services

## Describe the solution you'd like

Ideally, the Input Action used to initiate or cancel the Teleport event should be configurable in the Teleport System profile

- Initiate Action (input down) would cause a new teleport initiation and teleport line along the pointer pose
- Initiate Action (release) would cause the teleport to complete and move the player
- Cancel Action - would cause the teleport even to cancel, so that the Initiate action (release) would not cause a teleport

This should support any action, with the added advantage that if a Vector 2 action was selected, this would also enable the existing behavior of having a teleport direction too (but shouldn't be mandatory)

This would enable buttons to be used to activate teleport, as well as Hands poses

## Describe alternatives you've considered

The only alternative is for all devs to write their own implementation

## Additional context

Most Oculus titles and some Steam ones two only use a button for Teleport.  Hands implementations would also need this enhancement to allow for simple teleportation using hands poses.

**Comment by StephenHodgson** [comment]
I think this is already how it works, but the language is different

**Comment by StephenHodgson** [comment]
@FejZa was this addressed in your PRs?

**Comment by FejZa** [comment]
No, it does not address this. I think a lot of this is already implemented in that way or a similar way. Maybe it all comes down to letting the user configure the input action to use for teleportation in the new teleport system profile.

**Comment by StephenHodgson** [comment]
@SimonDarksideJ please review the new teleport changes and close this if you feel satisfied with the results.

**Comment by FejZa** [comment]
I am closing this as the requirements seem to be met. As discussed we will be adding a cancel action and proper locomotion upgrade in 0.3.
