### ISSUE TITLE
Add tooltip/message to Teleport System inspector, to denote that "None" means Instant Teleport

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#728]
# XRTK - Mixed Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

Having the teleport system default to "None" could cause confusion, as it actually means it is teleporting but instantly.

## How would you classify your suggestion

- Usability / Configuration

## Describe the solution you'd like

Add a simple message to the Teleport System inspector, so that when the Teleport Provider is set to None, it means the default "instant" teleportation system is enabled

**Comment by StephenHodgson** [comment]
We could also rename it to just "default"
