### ISSUE TITLE
New Locomotion System 

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#730]
# XRTK - Mixed Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

Currently, the XRTK focuses solely on Teleportation as a movement system, a legacy of its HoloToolkit routes.

However, going forward we need to update this to be a fully-fledged Locomotion system, that can handle multiple different types of movement patterns.

Handling such systems as:

* Teleportation (current)
* Forced locomotion (motion movement with a stick)
* Head-turning via a stick or touchpad (currently limited to teleportation Vector2 axis)
* Scene transition events (portals)
* Hybrid scenarios

## How would you classify your suggestion

- Usability / Configuration
- Architecture / Services

## Describe the solution you'd like

* It should be possible to have multiple Locomotion systems available and configure the active system by a users preference
* It should be possible to change the active Locomotion system via code
* The current active locomotion profile should be saved and recalled when a title is launched.
* It should be possible to navigate around a scene using Teleport pointers (straight, curved, etc), either instant, faded, or custom
* It should be possible to reorientate the camera view rotation using a stick or touchpad independently
* It should be possible to navigate around a scene using forced locomotion using a stick or touchpad, physically moving the camera
* It should be possible to target a hotspot and cause a Teleport event to another scene
* The locomotion system should also provide the ability to create a custom teleportation pattern

## Describe alternatives you've considered

Current system, teleportation only

**Comment by StephenHodgson** [comment]
Just to clarify this would essentially replace or rename the teleport system with locomotion, correct?

**Comment by FejZa** [comment]
> Just to clarify this would essentially replace or rename the teleport system with locomotion, correct?

Correct!
