### ISSUE TITLE
Importing platform configuration without a XRTK GO in a scene causes configuration corruption

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#739]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

If the platform auto-configuration helper runs when there is no MixedRealityToolikit GO in the scene, it corrupts the current configuration profiles and causes odd behavior in Unity

## To Reproduce

1. Create a new project
2. Register the XRTK upm server
3. Download the XRTK.SDK
4. Download a platform, e.g. Oculus
5. When prompted, say "Yes, Absolutely" to install the configuration
6. Try using "Mixed Reality Toolkit -> Configure"

## Expected behavior

Ideally, if no MixedRealityToolkit object exists, one should be created so that it can be configured.  EIther that or the user should be prevented from auto-configuring unless there is an existing GO

## Actual behavior

SDK configuration becomes corrupt and loses runtime platform options for configuration

## Your Setup

- Operation system Windows
- Unity Version 2019.4
- XRTK Version 0.2

## Additional context

The only way to avoid this scenario is to Configure a scene DIRECTLY after importing the SDK, as follows:
1. Create a new project
2. Register XRTK
3. Install SDK
4. Return to the scene and configure (Mixed Reality Toolkit -> Configure)
5. Open UPM Manager
6. Install a new platform
7. Say yes to the dress

**Comment by StephenHodgson** [comment]
> Ideally, if no MixedRealityToolkit object exists, one should be created so that it can be configured.

Might be better to not create the object unless explicitly created using "configure", but we should try to install any platforms when the configuration is manually ran
