### ISSUE TITLE
Refactor System level services to be registered using a collection in the root profile

### ISSUE THREAD

**Issue by StephenHodgson** [XRTK/XRTK-Core#764]
# XRTK - Mixed Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe
Currently each `IMixedRealitySystem` in the xrtk is registered individually in the root profile, but could be refactored to be easier to be simpler while adding the ability to give developers a way to register their own systems.

## How would you classify your suggestion
- Usability / Configuration
- Architecture / Services

## Describe the solution you'd like
Refactor the `MixedRealityToolkitRootProfile` to inherit from `BaseMixedRealityServiceProfile<T>` instead of `BaseMixedRealityProfile` so we can utilize the `RegisteredServiceConfigurations` collection for `IMixedRealitySystems`.

The `MixedRealityToolkit.InitializeServiceLocator` will also need to be refactored to utilize this collection, which would reduce the size and complexity of the method.

**Comment by FejZa** [comment]
Sounds good to me. Pretty much what I had in mind.

**Comment by StephenHodgson** [comment]
Yeah I think @SimonDarksideJ did a good job explaining it to me, but this is a big breaking change. Biggest challenge is doing A/B testing.
