### ISSUE TITLE
Installation failed on MacOS

### ISSUE THREAD

**Issue by ScarlettZ98** [XRTK/XRTK-Core#783]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

After downloading the XRTK via Manual UPM Installation, the package doesn't work with System.IO.FileNotFoundException in the console.

## To Reproduce

1. Download XRTK by manually modifying manifest.json as described in the tutorial.
2. Unity automatically resolves changes
3. 571 FileNotFoundException show in the console.
4. Mixed Reality ToolKit -> Configure only adds a MixedRealityToolKit object in the hierarchy, different from the expected result in the tutorial

## Expected behavior

No errors in the console and Mixed Reality ToolKit -> configure should create objects like MixedRealityPlayspace, PlayerBody, etc. 

## Actual behavior

571 FileNotFoundException show in the console. It seems the script use backslash which is widely used in Windows, but MacOS and Linux use slash.

## Screenshots

<img width="1462" alt="Screen Shot 2021-02-12 at 8 38 59 AM" src="https://user-images.githubusercontent.com/31007583/107775050-cf02c600-6d0d-11eb-80e6-81b7eae732b9.png">

## Your Setup

- MacOS Big Sur
- Unity 2019.4.20f1
- XRTK Core 0.2.6, XRTK SDK 0.2.3

**Comment by StephenHodgson** [comment]
Thanks for reporting this!

I'll be sure to update the package installer with the more appropriate file directory character separators.

**Comment by StephenHodgson** [comment]
https://github.com/XRTK/XRTK-Core/blob/353f7daf1006069aa1e5c54d588c1240e065697f/XRTK-Core/Packages/com.xrtk.core/Editor/PackageInstaller.cs#L187

Fairly certain it's bc we're missing the `.ToForwardSlashes()` call on the end of this line

**Comment by StephenHodgson** [comment]
Here's a bit more info from a thread on discord
![Screenshot_20210212-094428_Discord](https://user-images.githubusercontent.com/13334553/107782405-075ad200-6d17-11eb-91dd-bf6e5881977b.png)

**Comment by StephenHodgson** [comment]
Related discord thread
https://discord.com/channels/597064584980987924/696053083444346890/796429411527294987

**Comment by StephenHodgson** [comment]
@ScarlettZ98 fix will be in the next release 0.2.7

**Comment by ScarlettZ98** [comment]
Thank you so much! I will view the discord post to see if I can fix it temporarily or maybe wait for the next update.

**Comment by StephenHodgson** [comment]
@ScarlettZ98 there is a preview for 0.2.7.preview.1 out to test :) should be downloadable from the unity package manager
