### ISSUE TITLE
Does XRTK support hand tracking in an application which can be deployed to Hololens and Oculus, without any changes?

### ISSUE THREAD

**Issue by hammadshah38** [XRTK/XRTK-Core#792]
# XRTK - Mixed Reality Toolkit Request for Information

## What are you trying to achieve?
Developing an application which can be deployed to both hololens and oculus without any changes in the project.

## What have you already tried

I have not tried it. Need information before starting.

**Comment by StephenHodgson** [comment]
That is correct. No code changes required, and the UI/UX input handlers are platform agnostic

**Comment by hammadshah38** [comment]
> That is correct. No code changes required, and the UI/UX input handlers are platform agnostic

Thank you so much for your valuable response. One more question! Can we use PUN 2 with XRTK as normal for cross-platform multiplayer 'X'R games?

**Comment by StephenHodgson** [comment]
Yes, but we do plan to eventually add a networking system to help facilitate ease of use at some point. Only point of concern with pun is their heavy reliance on monobehaviors for components that don't really require to be invertible from it

**Comment by hammadshah38** [comment]
> Yes, but we do plan to eventually add a networking system to help facilitate ease of use at some point. Only point of concern with pun is their heavy reliance on monobehaviors for components that don't really require to be invertible from it

Thank you so much.
