### ISSUE TITLE
Updated MixedRealityToolkit instance inspector needs to include a "Basic" view, similar to Controllers

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#799]
# XRTK - Mixed Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

The updated MixedRealityToolkit root profile inspector, whilst improved, does lack a certain amount of usability and could benefit from a "Basic" view, similar to that used in Controler config

## How would you classify your suggestion

- Usability / Configuration

## Describe the solution you'd like
The current screen

![image](https://user-images.githubusercontent.com/1793042/110710573-0625a380-81f6-11eb-985c-b8d257c16e27.png)

Whilst functional for advanced users, could be simplified with a basic view that just has a button to view each systems registered configuration, in the same way with controllers, we have a basic view to just view the mappings for each controller as shown below:

![image](https://user-images.githubusercontent.com/1793042/110710677-353c1500-81f6-11eb-988b-6d946ca4cdc4.png)

## Describe alternatives you've considered
Current screen

**Comment by SimonDarksideJ** [comment]
Current status

Advanced
-----------
![Snag_369e27a](https://user-images.githubusercontent.com/1793042/120403584-62531c00-c33c-11eb-8eea-35e921c09518.png)

Basic
------
![Snag_369f43d](https://user-images.githubusercontent.com/1793042/120403593-64b57600-c33c-11eb-9861-7e14ff57fbf9.png)

Only thing left is the minor task of getting the editor to actually open the profile in the basic view :D

**Comment by SimonDarksideJ** [comment]
I'm no designer, we can update the textures to whatever we want.  I'll see what I can do about the sizing.

**Comment by StephenHodgson** [comment]
I think we should still have a way to assign a profile in at all times

**Comment by SimonDarksideJ** [comment]
If you want to change the current profile, then use the advanced view, simples

**Comment by StephenHodgson** [comment]
I also think the advanced column is a big misleading visually bc people will think it's the profiles off to the side that are advanced. Could we get another screenshot of then taking up a whole row each?

**Comment by SimonDarksideJ** [comment]
Updated look and feel from review comments. 
![Snag_5aa17a](https://user-images.githubusercontent.com/1793042/120468890-a1638a80-c399-11eb-9465-d07f92952d50.png)

**Comment by SimonDarksideJ** [comment]
WHen I tested using the entire Row @StephenHodgson , it looked very clunky and wasteful

**Comment by StephenHodgson** [comment]
Can we just as easily make the drop-down only if you click the arrow, and if you actually click the row you'd open the profile?

I still think even with two columns it still looks  too big and clucky. I'd much prefer a more compact look that looks more native to the editor style.
