### ISSUE TITLE
Remove current gLTF utility

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#800]
# XRTK - Mixed Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

Very simple, remove the current gLTF utilities from CORE.  They cause more issues than they solve.

Additionally, because it is part of Core, it makes it impossible for an XRTK user to use an alternative.

If we still want to provide our version, then it should be extracted into its own project and updated with the latest capabilities, etc

**Comment by FejZa** [comment]
"Additionally, because it is part of Core, it makes it impossible for an XRTK user to use an alternative."

I can see this being an issue and removing them makes sense.

You mention other issues. What are those?

**Comment by StephenHodgson** [comment]
Isn't this a duplicate?

I was gonna try to get around this pretty.

Afaik there's no real bickers besides the build window, but we could just make the gltf asset a prefab reference I suppose.

**Comment by SimonDarksideJ** [comment]
I think that issue @StephenHodgson should be moved to the separate project should we wish to continue it.

As to issues @FejZa , I have utterly failed to get gLTF models to load now and it complains about gLTF buffers being null.  Granted, these are streamed gLTF's, but I already had this working, but now (when I tested again this week) it utterly fails.

But primarily because this is in core, I can't use another solution without drastic measures.
