### ISSUE TITLE
MRTK assets having shaders issue in HDRP pipeline.

### ISSUE THREAD

**Issue by ashwinir05** [XRTK/XRTK-Core#846]
We are using HDRP pipeline with MRTK (V 2.6.2) for one of our project . All the MRTK assets such as buttons will appear pink , and shaders are also not editable in the Inspector window.

Some of the error messages are :
1.  Material 'Bronze - Polished' with Shader 'HDRP/Lit' doesn't have a float or range property '_FluentLightIntensity'
UnityEngine.Material:GetFloat (int)
Microsoft.MixedReality.Toolkit.UI.PressableButtonHoloLens2:Start () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@353cd524887a-1622549635005/SDK/Features/UX/Scripts/PressableButtons/PressableButtonHoloLens2.cs:83)

2.  Material 'Default-Line' with Shader 'Legacy Shaders/Particles/Alpha Blended Premultiply' doesn't have a float or range property '_BorderWidth'
UnityEngine.Material:GetFloat (int)
Microsoft.MixedReality.Toolkit.Utilities.MaintainBorderLightWidth:Start () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@353cd524887a-1622549635005/Core/Utilities/MaintainBorderLightWidth.cs:30)

3.  Material 'Bronze - Polished' with Shader 'HDRP/Lit' doesn't have a float or range property '_BorderWidth'
UnityEngine.Material:GetFloat (int)
Microsoft.MixedReality.Toolkit.Utilities.MaintainBorderLightWidth:Start () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@353cd524887a-1622549635005/Core/Utilities/MaintainBorderLightWidth.cs:30)

4.Material 'Bronze - Polished' with Shader 'HDRP/Lit' doesn't have a float or range property '_BorderWidth'
UnityEngine.Material:GetFloat (int)
Microsoft.MixedReality.Toolkit.Utilities.MaintainBorderLightWidth:Start () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@353cd524887a-1622549635005/Core/Utilities/MaintainBorderLightWidth.cs:30)

**Comment by StephenHodgson** [comment]
Unrelated to MRTK. Might want to re-open the issue over on Microsoft's repository.
