### ISSUE TITLE
Need a check on "TryGetService" when it is called from Awake, to avoid confusion by trying to get services too early

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#867]
# XRTK - Mixed Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

- Usability / Configuration

## Describe the solution you'd like
If TryGetService is called external from the XRTK, before the toolkit is initialised, it should throw a "NotInitialised" error with a helpful message, such as "The XRTK has not yet initialised, are you attempting to call it during awake?"

## Describe alternatives you've considered
User rolling around in confusion as to why their script does not work.

**Comment by StephenHodgson** [comment]
I suspect TryGet should just return false (as the name implies it could fail to return a valid instance of a service). Adding the errors could increase the log spam in unintended ways, even though it is a valid check.

Also you can wait until the xrtk is initialized (we have examples in several monobehaviour handlers like the [base input handler](https://github.com/XRTK/SDK/blob/development/XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/Input/InputSystemGlobalListener.cs#L38), or the [base controller pointer](https://github.com/XRTK/SDK/blob/development/XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Pointers/BaseControllerPointer.cs#L170), where we wait until the xrtk is initialized or when a system/service is initialized.

We can also encourage people to just simply check if the xrtk has been initialized (As there is a simple assert method on the type)

[`MixedRealityToolkit.AssertIsInitialized()`](https://github.com/XRTK/XRTK-Core/blob/development/XRTK-Core/Packages/com.xrtk.core/Runtime/Services/MixedRealityToolkit.cs#L344)

Probably the best method to use here is [`GetSystemAsync<IMixedRealitySystem>()`](https://github.com/XRTK/XRTK-Core/blob/development/XRTK-Core/Packages/com.xrtk.core/Runtime/Services/MixedRealityToolkit.cs#L1956) or [`GetServiceAsync<IMixedRealityService>()`](https://github.com/XRTK/XRTK-Core/blob/development/XRTK-Core/Packages/com.xrtk.core/Runtime/Services/MixedRealityToolkit.cs#L1621)
