### ISSUE TITLE
Move project folders from Assets to Packages

### ISSUE THREAD

**Issue by StephenHodgson** [XRTK/XRTK-Core#87]
In order to take full advantage of the upm system, our projects assets should be embedded in the `Packages` folder, not the assets folder.

# Requirements
- [x] Move the `ProjectRoot/XRTK-Core/Assets/XRTK` folder into to `ProjectRoot/XRTK-Core/Packages/XRTK/`
  - [x] Move all sub-projects to the same pattern
- [x] Update the CI git split-tree command to use the updated path.
- [x] Ensure that docfx builds correctly.

**Comment by StephenHodgson** [comment]
Unfortunately it doesn't look like Unity supports exporting traditional `.unitypackage`s from assets located in the Packages location, so we cannot move forward with this yet.

**Comment by SimonDarksideJ** [comment]
Well, as our preferred path is the UPM route (as it's far easier), we could proceed.  So Packages should be the default option.

If the community votes for a side by side .UnityAsset, it wouldn't be hard to create an asset that targets a different folder.

**Comment by StephenHodgson** [comment]
Yeah I'm thinking #103 should fix this issue for us
