### ISSUE TITLE
No readme info in upm default branch

### ISSUE THREAD

**Issue by StephenHodgson** [XRTK/XRTK-Core#88]
Currently to support upm we had to update the default branches to the upm specific one, unfortunately this also caused us to lose the nice readme landing page from dev/master.

**Comment by SimonDarksideJ** [comment]
So do we transfer the ReadMe to the UPM branch as well, or is this likely to have knock on issues.

Alternative would be to have a simple link follow to the main XRTK Core project Wiki (although for extensions that could get messy)

**Comment by StephenHodgson** [comment]
We do. I've already fixed it in the CI/CD workflows.

They copy the files and place them in the correct location at build time, then commits them back to the branch.
